import LeanRidgelet.HA.Quadratic
import LeanRidgelet.HA.QuadraticMeasure
import LeanRidgelet.HA.QuadraticRelativeMeasure
import LeanRidgelet.HA.QuadraticReconstruction
import LeanRidgelet.HA.QuadraticBounded
import LeanRidgelet.HA.QuadraticComposite
import LeanRidgelet.HA.QuadraticTransfer
import LeanRidgelet.HA.BochnerMeasurability
import LeanRidgelet.HA.QuadraticWeighted
import LeanRidgelet.HA.QuadraticParameterFactor
import LeanRidgelet.HA.QuadraticShear
import LeanRidgelet.HA.ParametricDerivMeasurable
import LeanRidgelet.HA.QuadraticSobolevSpace
import LeanRidgelet.HA.QuadraticSobolevCarrier
import LeanRidgelet.HA.QuadraticSobolevFourier
import LeanRidgelet.HA.QuadraticFiniteWidth
import LeanRidgelet.HA.QuadraticNonzero
import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false
-- Verso directive headers and display mathematics must stay on one physical line.
set_option linter.style.longLine false
set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Harmonic-analysis method: the quadratic-form network" =>
%%%
file := "ha-quadratic"
%%%

Section 7 of the article is the one architecture whose parameter space is not a copy of the data space, and it is where the formalization has the most to say. A quadratic form in the data followed by an arbitrary activation is jointly invariant under the affine group acting linearly on the coefficients, so the abstract reconstruction theorem applies once a balanced parameter measure exists; but the measure has to be built, the boundedness appendix cannot be used as written, and the route that replaces it is new analysis. This chapter follows that arc: the algebra, the two parameter measures, the endpoint from bounded intertwiners, the two square-integrability routes and the compactness obstruction that closes them, and then the intermediate coefficient space through which the analysis and the synthesis are bounded separately.

*The algebra and the parameter measures*

:::lemma_ "ha_quadratic_detail" (lean := "LeanRidgelet.symmetricSubmodule, LeanRidgelet.QuadraticSymmetric, LeanRidgelet.QuadraticParameter, LeanRidgelet.quadraticCongrEndo, LeanRidgelet.quadraticEval, LeanRidgelet.isSelfAdjoint_congr, LeanRidgelet.quadraticCongrMap, LeanRidgelet.quadraticCongrMap_coe, LeanRidgelet.quadraticCongr, LeanRidgelet.quadraticCongr_coe, LeanRidgelet.inner_quadraticCongr, LeanRidgelet.quadraticArgument, LeanRidgelet.quadraticFeature, LeanRidgelet.quadraticShearVector, LeanRidgelet.quadraticShearVector_apply, LeanRidgelet.quadraticLinearShear, LeanRidgelet.quadraticLinearEquiv, LeanRidgelet.quadraticSymmetricShear, LeanRidgelet.quadraticParameterLinearEquiv, LeanRidgelet.quadraticParameterLinearEquiv_apply, LeanRidgelet.quadraticArgument_invariant, LeanRidgelet.quadraticFeature_invariant, LeanRidgelet.quadraticArgument_parameter_injective, LeanRidgelet.quadraticParameterSMul, LeanRidgelet.quadraticParameterMulAction, LeanRidgelet.quadraticParameter_smul_def, LeanRidgelet.det_quadraticParameterLinearEquiv") (uses := "ha_affine_jacobian_detail, ha_joint_equivariance_constructors")
*Section 7.* A quadratic form in the data followed by an arbitrary activation, $`\sigma(x^\top A x + x^\top b + c)`, with the affine group acting on the data by $`x\mapsto Lx+t` and on the parameters by $`(A,b,c)\mapsto(L^{-\top}AL^{-1},\ L^{-\top}b-2L^{-\top}AL^{-1}t,\ c+t^\top L^{-\top}AL^{-1}t-t^\top L^{-\top}b)`.
:::

Symmetric matrices are self-adjoint continuous endomorphisms of the data space, so no basis is chosen and the transpose is the adjoint; they form a real subspace, which is what later puts a parameter measure on them. Writing $`s=L^{-1}t`, congruence turns every term into an inner product at the shifted point: the quadratic term becomes $`\langle x+s, A(x+s)\rangle`, the linear term $`\langle x+s, b-2As\rangle`, and the constant $`c-\langle s,b\rangle+\langle s,As\rangle`. Expanding, the cross terms cancel — this is where symmetry of $`A` is used, through $`\langle s,Ax\rangle=\langle x,As\rangle` — and the scalar argument of the activation is left invariant. Hence so is the feature, for every activation.

The parameter action is linear, not merely affine, and it is block lower triangular for the filtration by the symmetric coefficient and then the linear one: its determinant is the determinant of the congruence $`A\mapsto L^{-\top}AL^{-1}` on symmetric coefficients times $`(\det L)^{-1}`. The congruence determinant is left abstract, since the parameter measure only needs it to be a nonzero constant; its explicit value $`(\det L)^{-(m+1)}` is not used. That the action is a group action is not proved by composing the three block formulas but obtained from the invariance itself: a quadratic parameter is determined by its scalar functional — the constant is the value at the origin, the odd part determines the linear coefficient, and the even part determines the quadratic form, hence the symmetric coefficient by polarization — so two parameter transformations agreeing on all functionals are equal.
:::theorem "ha_quadratic_finite_width_detail" (lean := "LeanRidgelet.continuous_quadraticVectorFeature, LeanRidgelet.quadraticFeatureBoundedContinuous, LeanRidgelet.quadraticFeatureBoundedContinuous_apply, LeanRidgelet.exists_finite_quadraticNetwork_approx") (uses := "ha_quadratic_detail, mathlib_lipschitz_discretization")
*Appendix C at Section 7.* The synthesis integral over a compact family of quadratic parameters is approximated, to any accuracy and uniformly in the data, by a finite network with nonnegative weights.
:::

The general theorem is in the Mathlib candidate layer: a Lipschitz family of bounded continuous functions indexed by a compact metric space with a finite measure has its Bochner integral as a uniform limit of nonnegative-weighted finite sums. Instantiating it here needs two conditions on the activation, and both are the usual ones for a uniform-approximation theorem. Continuity, so that the feature is continuous in the data; and boundedness, so that the feature is an element of the space whose norm is the supremum norm.

An activation of polynomial growth is excluded, and for a reason worth stating plainly rather than working around: $`x\mapsto\sigma(q_\xi(x))` is then unbounded, so it is not an element of that space at all, and a uniform-in-$`x` approximation over an unbounded data space is not the statement one would want for it. The rectified linear unit belongs to the boundedness discussion below, not to this one.

The parameter side is indexed by an abstract compact metric space mapping into the parameter space, because the relatively invariant parameter measure is neither compact nor finite. That is the honest form of the statement: a finite network is a finite sum of features at finitely many parameters, and the theorem says the integral over any compact family is approximated by such a sum.

:::theorem "ha_quadratic_measure_detail" (lean := "LeanRidgelet.quadraticParameterLinearEquiv_one, LeanRidgelet.quadraticParameterLinearEquiv_mul, LeanRidgelet.quadraticParameterLinearEquiv_inv, LeanRidgelet.quadraticParameterJacobian, LeanRidgelet.quadraticParameterJacobian_one, LeanRidgelet.quadraticParameterJacobian_cocycle, LeanRidgelet.quadraticParameterJacobian_ne_zero, LeanRidgelet.quadraticParameterJacobian_eq_blocks, LeanRidgelet.quadraticParameter_measurable, LeanRidgelet.quadraticParameterJacobian_measurable, LeanRidgelet.quadraticParameter_map_eq_withDensity, LeanRidgelet.quadraticParameter_group_map_eq_withDensity, LeanRidgelet.quadraticParameterLpUnitaryRepresentation") (uses := "ha_quadratic_detail, ha_affine_jacobian_detail, ha_induced_l2_detail")
*Quadratic parameter measure.* The quasi-invariant `L²` representation of the affine group on quadratic parameters, with the constant Radon--Nikodym density of the parameter action.
:::

The parameter action is a linear automorphism of a finite-dimensional space, so pushing an additive Haar measure forward along it multiplies it by the absolute determinant, a nonzero constant. That determinant is exactly the density, so the Jacobian is defined intrinsically as the norm of the determinant of the parameter equivalence and never has to be evaluated; the ridge case is the same quantity written through the data determinant, since there the parameter determinant is $`(\det L)^{-1}`. The cocycle law comes from multiplicativity of the determinant along the composition law of the action, and that composition law is read off the group-action instance rather than recomputed from the three blocks. Non-vanishing is that the determinant of an equivalence is a unit, so the density is admissible for the quasi-invariant construction, which then supplies the unitary representation. The parameter space carries no global measurable structure: the measurable space and Borel structure of the symmetric coefficients are assumed, exactly as the data space assumes its own, and the product structure follows.

Here the quadratic feature parts company with the ridge one. The generic quasi-invariant synthesis and ridgelet identities require the parameter density to be the reciprocal of the data density, and for ridge parameters that holds exactly, the parameter determinant being $`(\det L)^{-1}` against the data determinant $`\det L`. For quadratic parameters the congruence factor survives, so the two densities differ by a positive character of the affine group, and a synthesis identity intertwines the parameter representation with a character-twisted data action rather than with the data representation. The twist does not cancel in the composite of synthesis with ridgelet: both halves pick up the same factor rather than reciprocal ones, so the composite carries its square, and a square equal to one forces the character to be one — that is, exact balance. So the twist has to be removed rather than tolerated, and the next node does that by changing the parameter measure. The article does not meet this point because it states the example in invariant-measure notation.

:::theorem "ha_quadratic_relative_measure_detail" (lean := "LeanRidgelet.quadraticSymmetricEquivSelfAdjoint, LeanRidgelet.det_quadraticCongr, LeanRidgelet.det_quadraticCongr_apply, LeanRidgelet.quadraticSymmetricDet, LeanRidgelet.quadraticSymmetricDet_smul, LeanRidgelet.quadraticNondegenerate, LeanRidgelet.preimage_smul_quadraticNondegenerate, LeanRidgelet.quadraticRelativeWeight, LeanRidgelet.quadraticRelativeWeight_smul, LeanRidgelet.quadraticRelativeParameterJacobian, LeanRidgelet.quadraticRelativeParameterJacobian_one, LeanRidgelet.quadraticRelativeParameterJacobian_cocycle, LeanRidgelet.quadraticRelativeParameterJacobian_ne_zero, LeanRidgelet.quadraticRelative_synthesis_radonNikodym_balance, LeanRidgelet.quadraticRelative_ridgelet_radonNikodym_balance, LeanRidgelet.nnnorm_det_quadraticParameterLinearEquiv, LeanRidgelet.quadraticRelativeMeasure, LeanRidgelet.quadraticRelative_map_restrict, LeanRidgelet.quadraticRelativeParameter_group_map_eq_withDensity, LeanRidgelet.quadraticRelativeParameterLpUnitaryRepresentation, LeanRidgelet.quadraticVectorFeature, LeanRidgelet.quadraticVectorFeature_jointInvariant, LeanRidgelet.quadraticRelativeBochnerSynthesis_intertwines, LeanRidgelet.quadraticRelativeBochnerRidgelet_intertwines") (uses := "ha_quadratic_measure_detail, mathlib_symmetric_congruence_det, mathlib_relatively_invariant_density")
*The balanced parameter measure of Section 7.* Weighting the parameter measure by a power of the determinant of the symmetric coefficient restores the balance the quadratic feature otherwise fails, and the two quasi-invariant Bochner identities then hold for it in their untwisted form.
:::

The determinant of the symmetric coefficient is a relative invariant: congruence multiplies it by the square of the determinant of the conjugating map, so under the parameter action it is multiplied by the inverse square of the determinant of the linear part. Raising it to the power $`-(m+1)/2` therefore produces a weight that the action multiplies by $`|\det L|^{m+1}`, and against the determinant of the parameter action, $`|\det L|^{-(m+2)}`, that leaves exactly $`|\det L|^{-1}` — the reciprocal of the data density, which is the balance. The exponent is forced: it is the only one that cancels, and it works for every dimension and every symmetric coefficient, with no case distinction.

Two things make this legitimate. The degenerate locus, where the weight blows up, is invariant under the action, so the measure is taken on its complement and the weight is finite and positive on the whole support; no null-set argument about a determinant hypersurface is needed. And the resulting measure is only σ-finite, not locally finite — for positive dimension the weight is not locally integrable across the degenerate locus — but nothing in the quasi-invariant construction or in the Bochner identities uses local finiteness, only σ-finiteness. The feature is re-bundled with values in a complex inner-product space, since the generic identities need that target, and its joint invariance is the scalar one read through the trivial output representation.

:::theorem "ha_quadratic_reconstruction_detail" (lean := "LeanRidgelet.quadraticReconstructionOperator_eq_smul_id, LeanRidgelet.quadraticNormalizedRidgelet_rightInverse, LeanRidgelet.quadratic_reconstruction, LeanRidgelet.affineData_quasiUnitaryPullbackAction_congr_ae, LeanRidgelet.quadraticRelative_quasiRegularAction_congr_ae, LeanRidgelet.quasiUnitaryPullbackAction_one_eq, LeanRidgelet.quadraticRelativeParameterLpUnitaryRepresentation_apply_ae, LeanRidgelet.quadraticSynthesisKernel, LeanRidgelet.quadraticAnalysisKernel, LeanRidgelet.quadraticMachine, LeanRidgelet.quadraticRidgelet, LeanRidgelet.norm_quadraticMachine_le, LeanRidgelet.norm_quadraticRidgelet_le, LeanRidgelet.coeFn_quadraticMachine, LeanRidgelet.coeFn_quadraticRidgelet, LeanRidgelet.quadraticMachine_intertwines, LeanRidgelet.quadraticRidgelet_intertwines, LeanRidgelet.quadraticEquivariantMachine, LeanRidgelet.quadraticEquivariantRidgelet, LeanRidgelet.quadratic_reconstruction_of_memLp") (uses := "ha_quadratic_relative_measure_detail, ha_reconstruction_detail, ha_affine_irreducibility, mathlib_hilbert_schmidt_kernel")
*Section 7, the endpoint.* The reconstruction operator of the quadratic-form network is a scalar multiple of the identity, and a nonzero scalar makes the normalized quadratic ridgelet transform a right inverse of the quadratic machine.
:::

The scalarity is Schur's lemma applied to the affine data representation, and its topological irreducibility is proved in this development rather than assumed, so the Section 7 conclusion rests on no placeholder. The parameter side is the relatively invariant model of the previous node, which is what makes the two representations balanced; with the additive Haar parameter measure they are not, and no such pair of intertwiners exists. Boundedness is no longer assumed. Reading the feature as an integral kernel, the Hilbert-Schmidt bound of the Mathlib candidate layer bundles each of the two integrals into a continuous linear map on `L²` whose operator norm is at most the `L²` norm of the feature, and the quasi-invariant Bochner identities upgrade them to intertwining maps. What is assumed instead is exactly the analytic input the article isolates in its boundedness appendix: that the feature is square integrable for the product of the data measure with the relatively invariant parameter measure. For a general activation that is false, so it cannot be proved.

The intertwining is proved as an equality of `L²` classes rather than pointwise, which is the level at which both the operators and the representations are defined: a class is an almost-everywhere equivalence class, and the pointwise Bochner identities enter through the almost-everywhere formulas for the two representations. Two small congruence facts are what make that work — each action respects almost-everywhere equality of representatives, because the inverse action is quasi measure preserving for the corresponding measure.

:::theorem "ha_quadratic_composite_detail" (lean := "LeanRidgelet.quadraticCompositeKernel, LeanRidgelet.quadraticCompositeOperator, LeanRidgelet.norm_quadraticCompositeOperator_le, LeanRidgelet.coeFn_quadraticCompositeOperator, LeanRidgelet.bochnerRidgelet_quadraticVectorFeature_congr_ae, LeanRidgelet.quadraticCompositeOperator_intertwines, LeanRidgelet.quadraticCompositeIntertwiner, LeanRidgelet.quadraticComposite_reconstruction") (uses := "ha_quadratic_reconstruction_detail, mathlib_hilbert_schmidt_kernel")
*The composite kernel, and why it is not the route to universality.* The reconstruction operator is bounded as soon as the composite kernel of the pair of features is square integrable, without either integral operator being bounded — but then the reconstruction constant is forced to vanish.
:::

Square integrability of the feature itself fails for every activation of polynomial growth, the rectified linear unit included: at a fixed parameter the integral of the squared feature over the data space already diverges. The article's other sufficient condition asks less, only that the composite kernel — the analysis feature paired against the synthesis feature and integrated over the parameter measure — be square integrable, and that is not automatically false. Fubini identifies the operator of that kernel with the pointwise composite of the Bochner synthesis and the Bochner ridgelet, and the two quasi-invariant identities make it an intertwining endomorphism of the data representation, so the reconstruction theorem applies with no boundedness hypothesis on either half.

The conclusion, however, is that the constant is zero. An operator with a square-integrable kernel is Hilbert-Schmidt, hence compact, while a scalar operator on an infinite-dimensional space is compact only for the zero scalar. The same argument applies a fortiori to square integrability of the feature, which makes both halves Hilbert-Schmidt. So neither condition can produce the nonzero constant universality needs, and that is why the L1 and L2 theories bound the two halves separately through a weighted intermediate space instead — a weighted parameter measure in one, transported coordinates with a weighted activation space in the other — where neither operator is Hilbert-Schmidt and the composite is bounded without being compact. For the quadratic feature that remains new analysis, and the weight has to go on the coefficient space, since the balance pins the parameter measure down.

:::lemma_ "ha_quadratic_transfer_detail" (lean := "LeanRidgelet.quadraticArgument_const_add, LeanRidgelet.hasDerivAt_quadraticAnalysisPairing, LeanRidgelet.hasDerivAt_bochnerRidgelet_quadraticVectorFeature, LeanRidgelet.iteratedDeriv_bochnerRidgelet_quadraticVectorFeature, MeasureTheory.eLpNorm_integral_weighted_le") (uses := "ha_quadratic_composite_detail")
*Transferring derivatives across the analysis transform.* The constant coefficient of a quadratic parameter enters the feature additively, so differentiating the analysis transform in it replaces the analysis feature by its derivative and changes nothing else.
:::

This is the step that escapes the compactness obstruction of the previous node. The analysis transform is a convolution in the constant coefficient, so a derivative in that coefficient can be moved onto the analysis feature; iterating gives, for a `k`-times differentiable analysis feature, that the `k`-th derivative of the transform is the transform of the `k`-th derivative feature. That iteration is proved, for a sequence of features each the derivative of the previous one. On the Fourier side in that variable it is multiplication by the `k`-th power of the frequency, so the transform lies in the space weighted by the `2k`-th power of the frequency, and the size of its norm there is controlled by the `k`-th feature together with the data. That exponent is the analogue of the smoothness index of the weighted activation spaces of the L2 theory; the growth index arises the same way, from multiplication by a polynomial in the constant coefficient, which on the Fourier side is a derivative. Neither weight can be moved onto the parameter measure, whose balance is already fixed, which is why they belong on the coefficient space.

The weighted estimate itself is recorded in the Mathlib candidate layer, together with the warning that a weight split between coefficient and feature by Cauchy--Schwarz is still a square-integrable kernel: the escape comes from the frequency weight and the orthogonality behind it, not from reweighting alone.

Joining the iterated transfer to the one-variable weighted Sobolev identity gives the estimate for each slice of the analysis transform in the constant coefficient: the frequency-weighted norm of the slice's angular Fourier transform is the Plancherel constant times the norm of the slice of the transform of the `k`-th feature. That is proved, for frozen values of the other two coefficients, with the hypotheses of both inputs threaded through and stated on the features rather than on the derivatives of the slice.

Integrating the slices over the remaining coefficients does not follow, and the reason is worth recording. The restriction and the density both factor through the symmetric coefficient alone, so they are not the problem; but the parameter measure is an abstract additive Haar measure on a triple product, which is not presented as a product over the constant coefficient, and after the Fourier transform the object lives over a space whose last coordinate is a frequency carrying Lebesgue measure rather than the restricted weighted measure. Beyond that bookkeeping, the exchange needs joint measurability of the transform in the parameter, and that is now available: both Bochner transforms are strongly measurable in the variable they produce, given a jointly measurable feature and an s-finite measure to integrate against, and for the quadratic feature the joint hypothesis is discharged by joint continuity of its scalar argument — evaluation of a continuous linear map is continuous in the pair, so the argument is continuous in data and parameter together. The measure bookkeeping is settled too: the degenerate locus and the weight read only the symmetric coefficient, so under the associativity transport the parameter measure becomes a positive multiple of a product over the constant coefficient, and an integral against it is the iterated integral that a Fubini step wants. So the measure poses no obstruction. What still separates the slice estimate from an integrated one is that the weighted side is a function of a frequency rather than of a constant coefficient, so there are not two functions on the same space to integrate — the remaining work is to say what the integrated statement should be, not to push a known one through.

:::lemma_ "ha_bochner_measurability_detail" (lean := "LeanRidgelet.aestronglyMeasurable_bochnerRidgelet, LeanRidgelet.stronglyMeasurable_bochnerRidgelet, LeanRidgelet.aestronglyMeasurable_bochnerSynthesis, LeanRidgelet.stronglyMeasurable_bochnerSynthesis, LeanRidgelet.continuous_uncurry_quadraticArgument, LeanRidgelet.continuous_uncurry_quadraticVectorFeature, LeanRidgelet.measurable_uncurry_quadraticArgument, LeanRidgelet.stronglyMeasurable_uncurry_quadraticVectorFeature, LeanRidgelet.measurable_uncurry_quadraticVectorFeature, LeanRidgelet.stronglyMeasurable_bochnerRidgelet_quadraticVectorFeature, LeanRidgelet.aestronglyMeasurable_bochnerRidgelet_quadraticVectorFeature") (uses := "ha_bochner_intertwining_detail, ha_quadratic_detail")
*Measurability of the transforms in the variable they produce.* Both Bochner transforms are strongly measurable, given a jointly measurable feature and an s-finite measure to integrate against; for the quadratic feature the joint hypothesis follows from joint continuity of its scalar argument.
:::

The transforms are raw Bochner integrals with no hypotheses attached, so nothing about them is measurable until said. The general statements are the ones the parametric-integral lemma of Mathlib gives, with the feature entered in the uncurried form that lemma consumes, and they are stated in the abstract setting so that the ridge feature is covered too. For the quadratic feature the joint hypothesis is not an assumption: its scalar argument is jointly continuous, because evaluating a continuous linear map is continuous in the operator and the vector together, so composing with a continuous or measurable activation gives what is needed. This is what the integration of the slice-wise weighted estimate was missing.

:::lemma_ "ha_quadratic_parameter_factor_detail" (lean := "LeanRidgelet.quadraticBaseDet, LeanRidgelet.quadraticSymmetricDet_eq_quadraticBaseDet, LeanRidgelet.quadraticBaseNondegenerate, LeanRidgelet.quadraticNondegenerate_eq_preimage, LeanRidgelet.quadraticBaseWeight, LeanRidgelet.quadraticRelativeWeight_eq_quadraticBaseWeight, LeanRidgelet.quadraticBaseRelativeMeasure, LeanRidgelet.measurable_quadraticBaseDet, LeanRidgelet.measurableSet_quadraticBaseNondegenerate, LeanRidgelet.measurable_quadraticBaseWeight, LeanRidgelet.exists_map_prodAssoc_symm_quadraticRelativeMeasure_eq_smul, LeanRidgelet.lintegral_quadraticRelativeMeasure_of_map_eq_smul, LeanRidgelet.exists_lintegral_quadraticRelativeMeasure_eq_mul_lintegral") (uses := "ha_quadratic_relative_measure_detail, mathlib_haar_prod_assoc")
*The parameter measure factors over the constant coefficient.* Under the associativity transport it is a positive multiple of a product of the corresponding measure on the other two coefficients with Lebesgue measure, so an integral against it is an iterated integral.
:::

The premise is that the degenerate locus and the weight read only the symmetric coefficient, which they do — both are conditions on its determinant, and the three compatibility statements are definitional. The general reassociation of the Mathlib candidate layer then applies, with one hypothesis the caller supplies: an additive Haar measure on the first two coefficients to compare against. There is no canonical choice, the parameter measure itself being abstract, and changing it only changes the constant.

This removes the measure obstruction to integrating the slice-wise weighted estimate. It does not integrate it: that is recorded above.

:::lemma_ "ha_quadratic_shear_detail" (lean := "LeanRidgelet.quadraticBaseLinearEquiv, LeanRidgelet.quadraticBaseLinearEquiv_apply, LeanRidgelet.quadraticConstShift, LeanRidgelet.quadraticConstShift_apply, LeanRidgelet.quadraticParameterLinearEquiv_apply_shear, LeanRidgelet.quadraticParameterLinearEquiv_eq_shear, LeanRidgelet.exists_quadraticParameterLinearEquiv_shear, LeanRidgelet.quadraticParameterLinearEquiv_apply_const_add, LeanRidgelet.quadraticConstSlice, LeanRidgelet.quadraticConstSlice_comp_smul, LeanRidgelet.hasDerivAt_quadraticConstSlice_comp_smul, LeanRidgelet.iteratedDeriv_quadraticConstSlice_comp_smul, LeanRidgelet.quadraticConstIteratedDeriv, LeanRidgelet.quadraticConstIteratedDeriv_comp_smul, LeanRidgelet.quadraticConstIteratedDeriv_comp_smul_eq, LeanRidgelet.eLpNorm_iteratedDeriv_quadraticConstSlice_comp_smul, LeanRidgelet.lintegral_comp_smul_quadraticRelativeMeasure, LeanRidgelet.lintegral_enorm_quadraticConstIteratedDeriv_comp_smul, LeanRidgelet.lintegral_base_enorm_quadraticConstIteratedDeriv_comp_smul") (uses := "ha_quadratic_parameter_factor_detail, ha_quadratic_transfer_detail")
*The parameter action is a shear in the constant coefficient.* The first two coefficients transform without reference to the third, and the third is itself plus a shift depending only on the other two — so differentiation in it commutes with the action, with no factor, and the Sobolev seminorms in it are carried along.
:::

This is what decides the design of the intermediate coefficient space. Since the action shifts the constant coefficient by an amount depending only on the other two, iterated differentiation in it commutes with the pull-back on the nose, and the norm of each derivative is unchanged slice by slice, by translation invariance of Lebesgue measure. Over the whole parameter measure the same identity holds with the constant that measure contributes on its own, the reciprocal of its Radon-Nikodym factor; combined with the factorization of the previous node it takes the iterated-integral shape a Sobolev space over the base would use, the factorization's own constant cancelling between the two sides.

So a Sobolev structure in the constant coefficient can be carried by the parameter representation, and the space it defines is the intermediate space through which the analysis and the synthesis are separately bounded — the point of the whole route, since such an operator need not be Hilbert-Schmidt. What this node establishes is that the structure is invariant; the two nodes below define the space and discharge the two measurability hypotheses carried here.

:::lemma_ "ha_parametric_deriv_measurable_detail" (lean := "LeanRidgelet.quadraticParameterPair, LeanRidgelet.quadraticConstPair, LeanRidgelet.continuous_quadraticParameterPair, LeanRidgelet.quadraticConstPair_slice, LeanRidgelet.quadraticConstIteratedDeriv_eq_parametric, LeanRidgelet.iteratedDeriv_quadraticConstSlice_eq_parametric, LeanRidgelet.contDiff_quadraticConstPair, LeanRidgelet.aestronglyMeasurable_iteratedDeriv_quadraticConstSlice_succ, LeanRidgelet.stronglyMeasurable_quadraticConstSlice, LeanRidgelet.aestronglyMeasurable_iteratedDeriv_quadraticConstSlice, LeanRidgelet.continuous_quadraticConstIteratedDeriv, LeanRidgelet.measurable_quadraticConstIteratedDeriv, LeanRidgelet.measurable_quadraticConstIteratedDeriv_succ, LeanRidgelet.measurable_quadraticConstIteratedDeriv_of_eq, LeanRidgelet.measurable_quadraticConstIteratedDeriv_bochnerRidgelet") (uses := "ha_quadratic_shear_detail, ha_quadratic_transfer_detail, mathlib_parametric_iterated_deriv")
*An iterated derivative in one coordinate of a parameter is measurable in the others.* Slice by slice this costs nothing; jointly in the parameter it is the continuity route, and for the analysis transform it is the derivative transfer.
:::

The two hypotheses the shear node carries are of very different difficulty, and only one of them has content. The slice-wise one is free: a derivative is measurable for every function, differentiable or not, because it vanishes off the differentiability set and that set is Borel, so iterating costs nothing and a positive order needs no hypothesis at all.

The one in the parameter has content, and there are two routes. Mathlib's parametric-derivative lemma is sharp for one step — joint continuity in, joint measurability out, with no differentiability assumed — but it cannot be iterated, because the continuity it consumes is not what it produces. The continuity route supplies that: the parametric derivative of a jointly smooth function is again jointly smooth, one order down, so an induction gives joint continuity of the parametric iterated derivative, and feeding that back into the one-step lemma gains an order. Reassociating the three coefficients of a quadratic parameter is a linear homeomorphism, so the general statements apply there unchanged.

Neither route sees the analysis transform, whose joint smoothness in the parameter is not known here. For it there is a third route, and it is the cheap one: its derivative in the constant coefficient *is* another analysis transform, by the transfer, and that one is measurable in the parameter by the Bochner measurability node. So for the one function the argument needs, the hypothesis is discharged from the transfer hypotheses alone.

:::lemma_ "ha_quadratic_sobolev_space_detail" (lean := "LeanRidgelet.quadraticConstIteratedDeriv_zero, LeanRidgelet.quadraticConstIteratedDeriv_apply, LeanRidgelet.quadraticConstIteratedDeriv_bochnerRidgelet, LeanRidgelet.quadraticSobolevSeminorm, LeanRidgelet.quadraticSobolevSeminorm_zero, LeanRidgelet.eLpNorm_quadraticConstIteratedDeriv_le_quadraticSobolevSeminorm, LeanRidgelet.eLpNorm_le_quadraticSobolevSeminorm, LeanRidgelet.quadraticSobolevSeminorm_mono, LeanRidgelet.MemQuadraticSobolev, LeanRidgelet.MemQuadraticSobolev.memLp, LeanRidgelet.quadraticSobolevSeminorm_comp_smul, LeanRidgelet.MemQuadraticSobolev.comp_smul, LeanRidgelet.quadraticBaseSobolevSeminorm, LeanRidgelet.quadraticBaseSobolevSeminorm_eq_lintegral, LeanRidgelet.quadraticBaseSobolevSeminorm_comp_smul, LeanRidgelet.exists_quadraticSobolevSeminorm_eq_mul_quadraticBaseSobolevSeminorm, LeanRidgelet.quadraticSobolevSeminorm_bochnerRidgelet, LeanRidgelet.memQuadraticSobolev_bochnerRidgelet, LeanRidgelet.enorm_bochnerSynthesis_le_quadraticSobolevSeminorm_mul, LeanRidgelet.measurable_quadraticConstIteratedDeriv_le_of_contDiff, LeanRidgelet.quadraticSobolevSeminorm_comp_smul_of_contDiff, LeanRidgelet.memQuadraticSobolev_of_contDiff, LeanRidgelet.memQuadraticSobolev_bochnerRidgelet_of_stronglyMeasurable") (uses := "ha_quadratic_shear_detail, ha_parametric_deriv_measurable_detail, ha_quadratic_parameter_factor_detail, mathlib_l2_duality")
*The intermediate coefficient space.* Order-`k` Sobolev in the constant coefficient of the parameter, over the parameter measure: the action scales its seminorm by the square root of the determinant of the linear part, the analysis transform's seminorm is computed by the features, and the synthesis integral is dominated by the seminorm.
:::

This is the space the boundedness route needs, and the seminorm is the sum over orders up to `k` of the parameter-`L²` norms of the derivatives in the constant coefficient. It is valued in the extended nonnegative reals, so it is defined for every coefficient function with no side condition, and membership is finiteness of it together with the measurability the previous node supplies. Two readings agree, up to the constant of the factorization: the global one over the parameter measure and the iterated one over the base, which is what makes the informal description a Sobolev-valued `L²` over the base literal.

Three statements make it an intermediate space rather than a definition. The action carries it, by the shear: the seminorm of a pull-back is the square root of the determinant of the linear part times the seminorm, at every order, so membership is preserved and the action is bounded on it with a known factor. The analysis side is an identity, not an estimate: the seminorm of the transform of the first feature is the sum of the parameter-`L²` norms of the transforms of the successive derivative features, so smoothness of the analysis feature is exactly what puts its transform in the space, and no Fourier transform appears in the statement. The synthesis side is Cauchy-Schwarz in the parameter, in dual form: the synthesis integral against a coefficient function is bounded at each data point by the seminorm times the parameter-`L²` norm of the synthesis feature there, and only the order-zero term of the seminorm is used, so the smoothness is spent entirely on the analysis side.

What is deliberately not done is the Hilbert-space packaging. There is a seminorm and a predicate on functions, not a normed space on equivalence classes: no quotient, no completeness, and the action is not promoted to a representation on a carrier. Nor is either operator's boundedness stated as an operator norm; what is proved are the two inputs such a statement is assembled from. The composite still needs a nonvanishing constant, and that is where the negative-order condition on the synthesis feature — the growth index, and where the rectified linear unit would have to be checked — remains open.

:::lemma_ "ha_quadratic_sobolev_carrier_detail" (lean := "LeanRidgelet.QuadraticSobolevCarrier, LeanRidgelet.norm_quadraticSobolevCarrier, LeanRidgelet.MemQuadraticSobolev.memLp_quadraticConstIteratedDeriv, LeanRidgelet.quadraticSobolevJet, LeanRidgelet.quadraticSobolevJet_component, LeanRidgelet.norm_quadraticSobolevJet, LeanRidgelet.quadraticSobolevJets, LeanRidgelet.quadraticSobolevSpace, LeanRidgelet.isClosed_quadraticSobolevSpace, LeanRidgelet.quadraticSobolevJet_mem_quadraticSobolevSpace, LeanRidgelet.contDiff_comp_quadraticParameterSMul, LeanRidgelet.contDiff_quadraticConstSlice, LeanRidgelet.quadraticConstIteratedDeriv_const_smul, LeanRidgelet.radonNikodymWeight_quadraticRelativeParameterJacobian_const, LeanRidgelet.quadraticConstIteratedDeriv_quasiRegularAction, LeanRidgelet.quadraticRelativeParameterLpIsometry, LeanRidgelet.quadraticRelativeParameterLpIsometry_apply, LeanRidgelet.quadraticSobolevCarrierAction, LeanRidgelet.quadraticSobolevCarrierAction_component, LeanRidgelet.norm_quadraticSobolevCarrierAction, LeanRidgelet.quadraticSobolevCarrierAction_one, LeanRidgelet.quadraticSobolevCarrierAction_mul, LeanRidgelet.contDiff_quasiRegularAction, LeanRidgelet.coeFn_quadraticRelativeParameterLpIsometry_toLp, LeanRidgelet.quadraticSobolevSeminorm_quasiRegularAction, LeanRidgelet.memQuadraticSobolev_quasiRegularAction, LeanRidgelet.quadraticSobolevCarrierAction_quadraticSobolevJet, LeanRidgelet.quadraticSobolevCarrierAction_mem_quadraticSobolevSpace, LeanRidgelet.quadraticSobolevSpaceAction, LeanRidgelet.quadraticSobolevSpaceAction_coe, LeanRidgelet.norm_quadraticSobolevSpaceAction, LeanRidgelet.quadraticSobolevSpaceActionMonoidHom, LeanRidgelet.quadraticSobolevContRepresentation, LeanRidgelet.quadraticSobolevContRepresentation_apply") (uses := "ha_quadratic_sobolev_space_detail, ha_quadratic_shear_detail, ha_quadratic_relative_measure_detail")
*The space as a Hilbert space, and the action on it.* The carrier is $`k+1` copies of parameter $`L^2` in the $`\ell^1` norm, so the norm of the tuple of derivatives *is* the seminorm; the space is the closure of the span of the tuples of the smooth members, hence complete; and the action is the diagonal of the parameter representation, hence isometric, and it carries the space.
:::

Three choices make this short. The **carrier** is a finite product of copies of parameter $`L^2` rather than anything new, because the seminorm is a sum of $`L^2` norms; and the product is taken in the $`\ell^1` norm, because then the norm of the tuple of derivatives is the seminorm on the nose — no equivalence of norms and no constants anywhere downstream. Completeness is then free: a finite product of complete spaces is complete, and the space is a closed subspace of it.

The **space** is the closure of the span of the tuples of the *smooth* coefficient functions of finite seminorm. That is forced, not chosen: the derivative of an almost-everywhere equivalence class is not defined, so a Sobolev space cannot be cut out of $`L^2` by a pointwise condition, and the alternative to a completion would be a theory of weak derivatives in the parameter, which this development does not have. Smoothness also makes the span meaningful, since the derivative of a sum is the sum of the derivatives only for differentiable summands.

The **action** is the diagonal of the parameter representation of the relatively invariant measure — no new representation is built. Two facts make the diagonal work. The representation's Radon--Nikodym weight is a *constant* in the parameter, the reciprocal square root of the determinant of the linear part, so it passes through a derivative; and the action is a shear in the constant coefficient, so the pullback commutes with the derivative. Together they say the tuple map is equivariant, and the diagonal of a unitary is an isometry of the $`\ell^1` product. The seminorm is therefore *exactly* preserved, in contrast with the plain pull-back, which scales it by the square root of that determinant: the weight is precisely the compensating factor.

Because the space is invariant, the action restricts to it, and the restriction is bundled as a representation of the affine group on the space — isometrically. That is what lets the reconstruction argument run *through* the intermediate space: a machine out of it and a ridgelet transform into it are intertwiners of representations, so Schur applies to their composite exactly as it does for parameter $`L^2`. It is also the only pair shape the two bounds can produce, since the synthesis is bounded on the space and not on parameter $`L^2`.

What this leaves for the boundedness statement is the factorization of the two Bochner integrals through the space. The analysis side has to land in it and the synthesis side has to be bounded on it; the estimates for both are stated as hypotheses in the endpoint chapter node below, and it is their promotion to operators on this carrier that the first of the two placeholders there still needs.

:::lemma_ "ha_quadratic_sobolev_fourier_detail" (lean := "LeanRidgelet.eLpNorm_pow_smul_angularFourier_quadraticConstSlice, LeanRidgelet.quadraticBaseSobolevSeminorm_eq_angularFourier, LeanRidgelet.angularFourierIntegralInner_comp_const_add") (uses := "ha_quadratic_sobolev_carrier_detail, ha_quadratic_transfer_detail, ha_quadratic_parameter_factor_detail")
*The two candidates were one space.* Plancherel in the constant coefficient turns the order-`k` Sobolev seminorm into a frequency-weighted $`L^2` norm of the angular Fourier transform, slice by slice and then over the base; and on the frequency side the data variable enters the synthesis pairing only as a phase.
:::

The intermediate space was designed in the constant coefficient rather than in its dual, because the action is a shear there and the Sobolev structure is therefore carried along — transporting to the dual side was the route not taken. This node shows the two routes describe the *same* space, so the choice was a choice of which side to make the invariance visible on. The invariance is visible in the constant coefficient, where the action is a shear. The synthesis bound is visible on the frequency side, where the activation appears through its own Fourier transform.

That is where the activation enters, and the shape is now explicit. For a frozen base parameter the synthesis integral is a pairing $`\int \gamma(c)\,\sigma(a+c)\,dc` with $`a` the part of the scalar argument free of $`c`, so the data variable enters only by translating the activation — and a translation is a phase on the frequency side. The pairing becomes an integral of the transform of the coefficient function against the transform of the activation, modulated by that phase, and the frequency weight $`|\zeta|^k` the seminorm carries is what has to absorb the singularity of the activation's transform. For the rectified linear unit that transform has a second-order pole at the origin, so $`k\ge 2` is the natural order. That is the negative-order condition on the synthesis feature, made concrete.

It is also why the synthesis bound is not a theorem yet, and the modulation identity is what shows it: an activation of polynomial growth has no Fourier transform as a function, the defining integral not converging, so *both sides of the identity degenerate to zero* for the rectified linear unit. The pairing is distributional and Parseval does not literally apply. A theorem needs a duality statement against the distributional transform. What the identity settles is the shape — data variable as phase, activation as a fixed frequency profile, order `k` as what pairs against it — and that shape is what a duality statement would have to be written against.

:::theorem "ha_quadratic_nonzero_detail" (lean := "LeanRidgelet.QuadraticMachine, LeanRidgelet.QuadraticRidgelet, LeanRidgelet.quadraticReconstructionScalar, LeanRidgelet.quadraticReconstructionOperator_eq_scalar_smul_id, LeanRidgelet.quadraticReconstruction_apply, LeanRidgelet.quadraticReconstructionScalar_ne_zero, LeanRidgelet.inner_quadraticReconstruction, LeanRidgelet.quadratic_reconstruction_nonzero_of_apply_ne_zero, LeanRidgelet.QuadraticAnalysisBound, LeanRidgelet.QuadraticSynthesisBound, LeanRidgelet.QuadraticCompositeEndomorphism, LeanRidgelet.eLpNorm_bochnerSynthesis_bochnerRidgelet_le, LeanRidgelet.exists_ne_zero_of_quadraticCompositeEndomorphism, LeanRidgelet.exists_quadraticCompositeIntertwiner_of_bounds, LeanRidgelet.exists_quadraticAdmissiblePair, LeanRidgelet.quadratic_reconstruction_nonzero, LeanRidgelet.quadratic_reconstruction_adjoint, LeanRidgelet.quadratic_bochner_reconstruction_adjoint, LeanRidgelet.QuadraticGammaMachine, LeanRidgelet.QuadraticGammaRidgelet, LeanRidgelet.quadratic_gamma_reconstruction, LeanRidgelet.quadratic_gamma_reconstruction_of_ne_zero") (uses := "ha_quadratic_sobolev_space_detail, ha_quadratic_reconstruction_detail")
*A nonzero reconstruction constant.* The Schur scalar is named and computed by any probe, so nonvanishing reduces to one datum having nonzero image; the two bounds through the intermediate space compose to a bound on the composite; and with an admissible pair the composite returns every datum multiplied by a nonzero constant.
:::

This is the shape of the article's universality claim, and it separates into a part that is proved and two analytic inputs that are not. What is proved: the reconstruction operator is its scalar times the identity; the pairing of a datum with its reconstruction is that scalar times the datum's squared norm, so the scalar is the pair's admissibility constant and not an artifact of the choice naming it; a single datum with nonzero image forces the scalar to be nonzero, hence gives the reconstruction outright, for a pair of intertwiners and for an endomorphism alike; and **the composite estimate**, which is the inequality the whole route exists to produce. None of that carries a placeholder.

The composite estimate deserves its statement read carefully. It says the composite of the two Bochner integrals is bounded on data $`L^2` by the product of the two constants — and it does *not* say that either factor is bounded on parameter $`L^2`. The synthesis is bounded on $`\Gamma^k`, which is smaller, the seminorm dominating the $`L^2` norm rather than the other way round. That asymmetry is the whole escape from the compactness obstruction, and it also fixes the shape of what remains: what the two bounds produce is a bounded intertwining **endomorphism** of data $`L^2`, the article's weaker reading of its own boundedness hypothesis, not a bounded pair through parameter $`L^2`. An earlier version of this development asked for the pair, which those bounds cannot give.

So one placeholder remains on the boundedness side: that the composite is realized by such an endomorphism. What is missing there is not the estimate, which is proved, nor the equivariance, which is available pointwise, but the packaging of a pointwise formula as an operator — almost-everywhere additivity of each of the two integrals. The other placeholder is the admissibility statement.


**A nonzero constant is reached, by the coorbit route.** Take the machine to be the adjoint of the ridgelet transform and the endpoint follows with no placeholder at all: one datum with nonzero transform gives a nonzero constant, the reconstruction operator is that constant times the identity, and the normalized ridgelet transform is a right inverse of the machine — the article's endpoint for Section 7, proved. The general statement and the reference are in the reconstruction chapter. What it costs is that the machine is the adjoint rather than an activation fixed in advance: at the level of the Bochner formulas that is the common-feature case, so this reconstructs with the network whose activation is the analysis feature. And the endpoint is available on the network's *own* integrals, not only on abstract operators: taking the synthesis feature to be the analysis feature makes the two Bochner integrals adjoint, so one datum with nonzero transform gives a nonzero constant for which the composite of the two integrals returns every datum multiplied by it. That is Section 7's claim written on the integrals the article writes down, with no placeholder — the hypotheses are the standing ones for analytic input, one Fubini condition, and the probe. The two placeholders above are about the harder problem, an activation fixed in advance.

The endpoint is also available with the intermediate space as the parameter space: a machine out of $`\Gamma^k` and a ridgelet transform into it compose to a scalar, and a probe makes the scalar nonzero. That is the pair shape the two bounds can produce — the synthesis is bounded on $`\Gamma^k`, not on parameter $`L^2` — and it carries no placeholder either, the Schur step needing only the irreducibility of the data representation and the representation on the space being now bundled.

The admissibility statement is an existence over pairs deliberately. For a fixed pair it is false — the zero synthesis feature satisfies both bounds and annihilates every datum — so quantifying over all pairs satisfying the bounds would place a false statement behind a placeholder. The article fixes the activation to be the rectified linear unit, and specializing the existence to a fixed activation is the follow-up: it needs the activation's nonvanishing on the Fourier side together with the negative-order condition that controls its growth. Neither is assumed here, and no boundedness and no nonvanishing constant appear as hypotheses of the endpoint.
