import LeanRidgelet.OverviewFS
import LeanRidgelet.ToMathlib.LieGroup.Hyperbolic
import LeanRidgelet.ToMathlib.LieGroup.PositiveDefinite
import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false
-- Verso directive headers and display mathematics must stay on one physical line.
set_option linter.style.longLine false
set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Fourier slice method: arXiv:2402.15984 implementation map" =>
%%%
file := "overview-fs"
%%%

The definitions and numbered results of

> S. Sonoda, I. Ishikawa and M. Ikeda, *A unified Fourier slice method to derive ridgelet transform for a variety of depth-2 neural networks*, arXiv:2402.15984,

in publication order, each linked to the declaration carrying it. This chapter is the place to check what of that article is formalized.

Where the other two developments establish what the ridgelet transform of a depth-2 fully-connected network on a Euclidean space is, this one abstracts the derivation and runs it on other input domains. The article's contribution is a three-step procedure: turn the network into its *Fourier expression*, *change variables* in the scale parameter so that the feature map splits into a principal and an auxiliary factor, and close with a *separation-of-variables* ansatz for the unknown coefficient function. Accordingly the formalization centres on one conditional theorem carrying the three steps, and each case supplies an inversion formula on its own domain, the Jacobian of the change of variables, and the integrability needed to exchange the order of integration. An inversion formula out of reach of the current Mathlib enters as an explicit hypothesis of a theorem; it is never a structure field, a typeclass field, or an axiom.

*Status: Sections 2--7 are complete except for the inversion formula of Section 5, which Lean takes as a hypothesis; Section 6 has its transform, its slice theorem, its inversion formula and all three of its reconstruction formulas — over the Stiefel manifold, over the similitude group and over all full-column-rank matrices — in every codimension.* The measure theory the general codimension needs is in the `ToMathlib / Invariant geometry` page, none of it being in Mathlib. Nodes with no Lean declaration record what is still to be proved. Three nodes carry a `sorry`: the Jacobian of the singular value decomposition, and the Helgason--Fourier inversion formula on each of real hyperbolic space and the manifold of positive definite matrices. No proof in the development depends on either.

*Section 2: the method*

:::definition "fs_pairing" (lean := "LeanRidgelet.fourierSlicePairing")
*The Fourier slice pairing.* For a scale dimension $`r`, an activation spectrum $`\sigma^\sharp` and a ridgelet spectrum $`\rho^\sharp`,
$$`(\!(\sigma,\rho)\!)_r:=\frac{1}{2\pi}\int_{\omega\neq0}\sigma^\sharp(\omega)\overline{\rho^\sharp(\omega)}\,|\omega|^{-r}\,\mathrm d\omega.`
This one scalar is the factor left in front of the reconstructed function in every case of the article: only $`r`, the dimension of the scale variable, changes. What differs between the cases is not the pairing but the normalization of the inversion formula, which the separation-of-variables ansatz absorbs into the coefficient function. The restriction to $`\omega\neq0` is where the change of variables $`\boldsymbol a\mapsto\omega\boldsymbol a` is a bijection; over $`\mathbb R` the excluded point is null, which is why the article leaves the restriction implicit.
:::

:::theorem "fs_method" (lean := "LeanRidgelet.fourierExpressionSynthesis, LeanRidgelet.separationOfVariables, LeanRidgelet.inversionIntegral, LeanRidgelet.fs_changeOfVariables, LeanRidgelet.fs_slice_of_inversion, LeanRidgelet.sliceSynthesis, LeanRidgelet.fs_fourierExpression_of_bias, LeanRidgelet.fs_reconstruction_of_inversion") (uses := "fs_pairing, mathlib_iterated_fubini")
*The three steps.* Given a domain $`X`, a direction space $`U`, a composite distance $`\pi:X\times U\to V` into a finite-dimensional real inner product space, a weight $`w`, Fourier data $`F` and an inversion density $`\kappa` satisfying the inversion formula $`f(x)=\int F(\lambda,u)\kappa(\lambda)e^{i\langle\lambda,\pi(x,u)\rangle}w(x,u)`, the network in Fourier expression form, evaluated at the separation-of-variables coefficient $`\gamma^\sharp(a,u,\omega)=F(\omega a,u)\kappa(\omega a)\overline{\rho^\sharp(\omega)}`, equals $`(\!(\sigma,\rho)\!)_r\,f` with $`r=\dim V`.
:::

That inversion formula is the *only* hypothesis of the reconstruction theorem: no integrability condition appears in it. Substituting the ansatz makes the bias frequency factor out of both inner integrals as a constant, so that proof never exchanges an order of integration, and the change of variables of Step 2 holds for every integrand because both sides degenerate together.

Step 1, which turns the network as the article writes it into the Fourier expression above, is where the analysis and the integrability live. Its analytic input is one-dimensional — at a fixed weight and direction, convolving in the bias and inverting — and is a hypothesis, since which form of it is available depends on the class the activation is taken from. It is discharged for an integrable activation over $`\mathbb R` and, as a finite-sum identity, over a finite field. The rest is Fubini, moving the bias frequency outside the weight and direction integrals, which is the article's standing assumption that the triple integral converges absolutely.

:::theorem "fs_reconstruction_euclidean" (lean := "LeanRidgelet.fs_inversionIntegral_euclidean, LeanRidgelet.fs_reconstruction_euclidean") (uses := "fs_pairing, fs_method")
*Reconstruction formula for the fully-connected network (Theorem 1.1).* The Euclidean instance of the method: the direction space is a point, so the weight is a plain vector of $`\mathbb R^m`, the composite distance is the identity, the weight function is $`1`, and the Jacobian exponent is $`r=m`. What remains is the inversion density $`\kappa=(2\pi)^{-m}`, which is the hypothesis.
:::

:::theorem "fs_euclidean_agreement" (lean := "LeanRidgelet.fs_separationOfVariables_euclideanRidgeletTransform, LeanRidgelet.fs_admissibilityConstant_eq_fourierSlicePairing") (uses := "fs_reconstruction_euclidean, l1_fourier_expression, l1_admissibility")
*Agreement with the L1 development.* Two identities check the abstraction against a formalization that predates it and was built independently. The separation-of-variables ansatz, specialized to the Euclidean setting at homogeneity index $`s=0`, is exactly the Fourier expression $`eq:fstridge` of the classical ridgelet transform; and the L1 admissibility constant is $`(2\pi)^m` times the Fourier slice pairing of the same two spectra.
:::

The factor $`(2\pi)^m` is not a discrepancy but the place where the normalization of the inversion formula sits: the article's coefficient function does not carry the inversion density, so its constant part ends up in the article's $`(\!(\sigma,\rho)\!)`, whereas the ansatz here carries $`\kappa`. The article itself states the Euclidean constant without the factor $`(2\pi)^{m-1}` in Section 1 and with it in Section 2; the latter is the one consistent with the derivation and with the L1 development.

*Section 3: networks on a finite field*

:::definition "fs_finite_field_network" (lean := "LeanRidgelet.finiteFieldSynthesis, LeanRidgelet.finiteFieldRidgelet, LeanRidgelet.finiteFieldPairing")
*Network, ridgelet transform and scalar on $`\mathbb F_p^m`.* $`S[\gamma](x)=\sum_{(a,b)}\gamma(a,b)\sigma(a\cdot x-b)`, $`R[f;\rho](a,b)=\sum_xf(x)\overline{\rho(a\cdot x-b)}`, and $`(\!(\sigma,\rho)\!)=|\mathbb F_p|^{m-1}\sum_{\omega\neq0}\sigma^\sharp(\omega)\overline{\rho^\sharp(\omega)}`, all sums finite. The dimension is `Fintype.card ι`, and the scalar is written with $`p^m/p` so that it is also correct for $`m=0`.
:::

:::theorem "fs_finite_field_reconstruction" (lean := "LeanRidgelet.fs_finiteField_synthesis_ridgelet, LeanRidgelet.fs_finiteField_reconstruction, LeanRidgelet.fs_finiteField_reconstruction_meanZeroPart") (uses := "fs_finite_field_network, fs_finite_field_steps")
*Reconstruction formula over a finite field (Theorem 3.2).* For $`\rho` of vanishing mean, $`S[R[f;\rho]]=(\!(\sigma,\rho)\!)f`. Without that hypothesis the master identity computes what is left over: $`S[R[f;\rho]]=(\!(\sigma,\rho)\!)f+|\mathbb F_p|^{m-1}\sigma^\sharp(0)\overline{\rho^\sharp(0)}\sum_yf(y)`. Subtracting its mean makes any $`\rho` usable and leaves the scalar unchanged.
:::

:::theorem "fs_finite_field_steps" (lean := "LeanRidgelet.fs_finiteField_fourierExpression, LeanRidgelet.fs_finiteField_changeOfVariables, LeanRidgelet.fs_dft_finiteFieldRidgelet") (uses := "fs_finite_field_network")
*The three steps over a finite field.* Step 1, the Fourier expression $`S[\gamma](x)=p^{-1}\sum_{a,\omega}\gamma^\sharp(a,\omega)\sigma^\sharp(\omega)\mathrm e(\omega\,a\cdot x)`, from the convolution theorem in the bias. Step 2, the change of variables $`\xi=\omega a`, valid for $`\omega\neq0` because $`\mathbb F_p` is a field — this is the only place primality is used. Step 3, the separation-of-variables form $`\gamma^\sharp(a,\omega)=\widehat f(\omega a)\overline{\rho^\sharp(\omega)}` of the ridgelet transform, obtained by reindexing the bias.
:::

Two deviations from the article are recorded here. The constant carries $`|\mathbb F_p|^{m-1}`, as in the article's own proof, rather than its reciprocal as in the article's statement. And the frequency $`\omega=0` has to be excluded: the change of variables $`a\mapsto\omega a` is a bijection of $`\mathbb F_p^m` only for $`\omega\neq0`, and over a finite field the excluded frequency is an atom rather than a null set, so it contributes a rank-one defect $`|\mathbb F_p|^{m-1}\sigma^\sharp(0)\overline{\rho^\sharp(0)}\sum_yf(y)`. Requiring $`\rho` to have vanishing mean kills it, which is the discrete counterpart of the admissibility condition of the continuous theory and the usual vanishing-moment convention for a wavelet. Any $`\rho` can be used after subtracting its mean, which changes neither the constant nor the conclusion.

*Section 4: group convolutional networks on a Hilbert space*

:::definition "fs_gconv_network" (lean := "LeanRidgelet.frameCoord, LeanRidgelet.frameVector, LeanRidgelet.frameProjection, LeanRidgelet.groupConvolution, LeanRidgelet.groupConvSynthesis, LeanRidgelet.groupConvRidgelet, LeanRidgelet.IsGroupEquivariant")
*Generalized group convolution and the group CNN.* For a representation $`T:G\to GL(\mathcal H)`, the convolution $`(a*x)(g)=\langle T_{g^{-1}}[x],a\rangle_{\mathcal H}`, the network $`S[\gamma](x)(g)=\int\gamma(a,b)\sigma((a*x)(g)-b)`, with the filter $`a` ranging over the span of an orthonormal $`m`-frame, and the ridgelet transform $`R[f;\rho](a,b)=\int_{\mathcal H_m}f(x)(e)\overline{\rho(\langle a,x\rangle-b)}`. The filter and the domain of the ridgelet integral are parametrized by their coordinates in the frame, which is what the article means by the Lebesgue measure on $`\mathcal H_m` induced from $`\mathbb R^m`.
:::

:::theorem "fs_gconv_reconstruction" (lean := "LeanRidgelet.fs_inner_frameVector, LeanRidgelet.fs_groupConvSynthesis_eq_euclidean, LeanRidgelet.fs_groupConvSynthesis_equivariant, LeanRidgelet.fs_groupConv_synthesis_ridgelet, LeanRidgelet.fs_groupConv_reconstruction") (uses := "fs_gconv_network, fs_reconstruction_euclidean")
*Reconstruction formula for the group CNN (Theorem 4.2).* The case reduces exactly to the Euclidean one: pairing a filter of $`\mathcal H_m` against any input is pairing their coordinate vectors, so the network is a Euclidean network read at the coordinate vector of the translated input, and the ridgelet transform is the Euclidean ridgelet transform of the target pulled back to those coordinates. The network is equivariant by construction. The master identity is then $`S[R[f;\rho]](x)(g)=(\!(\sigma,\rho)\!)f(P_{\mathcal H_m}(T_{g^{-1}}[x]))(e)` with no hypothesis on $`f`, and equals $`(\!(\sigma,\rho)\!)f(x)(g)` whenever the projection is invisible to $`f` at that point.
:::

Whichever Euclidean reconstruction formula one has is a hypothesis of the two last declarations rather than a fixed choice, so the case does not commit to one analytic setting.

:::theorem "fs_gconv_projection_structural" (lean := "LeanRidgelet.fs_groupConvSynthesis_congr_frameCoord, LeanRidgelet.fs_frameProjection_eq_self_of_mem, LeanRidgelet.fs_mem_of_invariant, LeanRidgelet.fs_span_orbit_le_of_invariant, LeanRidgelet.fs_not_finiteDimensional_of_orthonormal_orbit") (uses := "fs_gconv_reconstruction")
*The projection is a limit of the architecture, and what delimits the ways around it.* The value of the network at $`(x,g)` depends on the input only through the coordinate vector of $`T_{g^{-1}}[x]`, for every coefficient function; so two inputs with the same coordinates are indistinguishable to every network of this form, and no choice of coefficient function reproduces a target that separates them. The projection in the master identity is therefore not an artifact of the proof.
:::

Sufficient conditions for the compatibility hypothesis: the translated input already lies in the span of the frame; or that span is $`T`-invariant and the input lies in it; or $`f` factors through the projection. The second is the natural one and comes with a caveat the article does not raise — it needs a *finite-dimensional* invariant subspace. The orbit of a vector of an invariant subspace stays inside it, so a vector whose translates span an infinite-dimensional space lies in no finite-dimensional invariant subspace. Such subspaces are plentiful when the closure of the image of $`T` is compact, as for a finite group, for $`\mathbb T` acting on Fourier modes, or for DeepSets; for a representation whose orbit of some vector contains an infinite orthonormal family — the integer translates of an indicator function under translation on $`L^2(\mathbb R)`, say — no finite-dimensional invariant subspace contains that vector at all, and only the pointwise hypothesis or a band-limited $`f` remains.

The projection is a deviation from the article, which states the conclusion as $`(\!(\sigma,\rho)\!)f`. Only an inversion formula on $`\mathcal H_m` is available, so what the derivation returns is the target function read at $`P_{\mathcal H_m}(T_{g^{-1}}[x])`. This is not an artifact of the proof: the network sees $`x` only through $`\langle T_{g^{-1}}[x],a\rangle` with $`a\in\mathcal H_m`, hence only through that projection, so no coefficient function can do better. Sufficient conditions for the two to agree are that $`T_{g^{-1}}[x]\in\mathcal H_m`, that $`\mathcal H_m` be $`T`-invariant, or that $`f` factor through the projection. The second is the natural one, but it needs a *finite-dimensional* invariant subspace, which exists in abundance when the closure of the image of $`T` is compact and only trivially when $`T` has no finite-dimensional subrepresentation.

*Section 5: networks on a noncompact symmetric space*

:::definition "fs_symmetric_network" (lean := "LeanRidgelet.horosphericalWeight, LeanRidgelet.harishChandraDensity, LeanRidgelet.symmetricSynthesis, LeanRidgelet.symmetricRidgelet, LeanRidgelet.symmetricFourierExpression")
*The network on $`G/K`, and the geometry it needs.* $`S[\gamma](x)=\int\gamma(a,u,b)\sigma(a\langle x,u\rangle-b)e^{\varrho\langle x,u\rangle}` and $`R[f;\rho](a,u,b)=\int_X c[f](x)\overline{\rho(a\langle x,u\rangle-b)}e^{\varrho\langle x,u\rangle}\,\mathrm dx`, with $`\langle x,u\rangle\in\mathfrak a\cong\mathbb R^r` the vector-valued composite distance from the origin to the horosphere through $`x` with normal $`u\in\partial X`.
:::

Mathlib has no Iwasawa decomposition, no spherical functions and no Harish-Chandra $`c`-function, and none is needed to state this. The geometry enters as data: the composite distance, the constant $`\varrho`, the density $`|W|^{-1}|c(\lambda)|^{-2}`, and the Helgason--Fourier transform of the target.

:::theorem "fs_symmetric_inversion" (lean := "SymmetricSpace.HasHelgasonInversion, SymmetricSpace.hasHelgasonInversion_iff, SymmetricSpace.hasHelgasonInversion_of_spherical") (uses := "fs_symmetric_network, mathlib_helgason_inversion")
*Helgason--Fourier inversion (Section 5).* $`f(x)=|W|^{-1}\int_{\lieA^{*}\times\partial X}\widehat f(\lambda,u)\,e^{(i\lambda+\varrho)\langle x,u\rangle}\,\mathrm d\lambda\,\mathrm du/|c(\lambda)|^{2}`. This is a *statement*, not a theorem: it is a predicate on the geometry, and proving it for a given space is a project of its own.
:::

`FS.Symmetric` takes the geometry as data, and with that data free the inversion formula is not a true proposition at all — which is why it was for a time not stated in Lean. The Mathlib-general layer now supplies the vocabulary to state it: the Helgason--Fourier transform, the spherical function and the Plancherel density built from $`|W|` and the `c`-function. What the statement is worth is that it can now be *reduced*: the last declaration shows the inversion formula follows from the identification of the boundary integral with the convolution against the spherical function together with Harish-Chandra's inversion formula for the spherical transform, so the deep analytic input is isolated to one hypothesis. The reconstruction formula below takes the inversion formula itself as an explicit hypothesis, which is the whole design of the abstract scheme.

:::definition "fs_symmetric_hyperbolic" (lean := "HyperbolicSpace.poincareBall, HyperbolicSpace.idealBoundary, HyperbolicSpace.poissonKernel, HyperbolicSpace.compositeDistance, HyperbolicSpace.rho, HyperbolicSpace.invariantMeasure, HyperbolicSpace.compositeDistance_origin, HyperbolicSpace.exp_compositeDistance, HyperbolicSpace.boundaryMeasure, HyperbolicSpace.helgasonFourier, HyperbolicSpace.HasInversion, HyperbolicSpace.mobius, HyperbolicSpace.compositeDistance_mobius, HyperbolicSpace.lintegral_invariantMeasure_comp_mobius, LeanRidgelet.hyperbolicWeight, LeanRidgelet.fs_hyperbolicWeight_eq_poissonKernel_rpow, LeanRidgelet.hyperbolicSynthesis, LeanRidgelet.hyperbolicRidgelet, LeanRidgelet.hyperbolicFourierExpression, LeanRidgelet.fs_hyperbolic_reconstruction_of_inversion, LeanRidgelet.fs_hyperbolicHelgasonInversion") (uses := "fs_symmetric_inversion, fs_symmetric_reconstruction, mathlib_hyperbolic_ball, mathlib_hyperbolic_mobius, mathlib_hyperbolic_mobius_measure, mathlib_hyperbolic_helgason_fourier")
*Continuous horospherical hyperbolic network (Section 5).* The Poincaré ball $`\mathbb B^m` with the metric $`4(1-|x|^2)^{-2}\sum\mathrm dx_i\otimes\mathrm dx_i`, composite distance $`\langle x,u\rangle=\log\frac{1-|x|^2}{|x-u|^2}`, $`\varrho=(m-1)/2`, boundary $`\mathbb S^{m-1}`, $`|W|=2`, and $`c(\lambda)` an explicit ratio of Gamma functions. Rank one, so everything is a closed formula and no Lie theory is needed; this is the first place the inversion formula above could be proved rather than assumed. The model itself is now in Lean — the ball, its boundary, the Poisson kernel, the composite distance, $`\varrho` and the invariant measure — with no Riemannian geometry used, since Mathlib has neither a volume measure nor a Laplace--Beltrami operator to build one from. The Helgason--Fourier transform of the model is there too, and with it the inversion formula as a *proposition* — `HyperbolicSpace.HasInversion`, a definite claim about a definite space rather than a schema. The Möbius action is there as well, together with the cocycle $`\langle\varphi_a x,\varphi_a u\rangle=\langle x,u\rangle-\langle a,u\rangle` that makes the isometry group act on the transform. The invariance of the volume measure under that action is there too, so the model is complete as a measured space with a group acting on it. On top of it the network, the ridgelet transform and the reconstruction formula of this example are formalized: `fs_hyperbolic_reconstruction_of_inversion` assumes the Helgason--Fourier inversion formula for $`\mathbb H^m` *and nothing else*, and that formula is `fs_hyperbolicHelgasonInversion`, the one remaining target. One by-product settles a design question the development plan had left open: the weight the layer carries is $`P(x,u)^\varrho`, a power of the Poisson kernel, hence a half-density rather than an input-dependent coefficient.
:::

:::definition "fs_symmetric_spd" (lean := "Matrix.cornerDet, Matrix.cornerDet_conj_of_lowerTriangular_unit, Matrix.cornerDet_conj_diagonal_sign, Matrix.cornerDet_of_ldl, SpdSpace.ofUpper, SpdSpace.invariantMeasure, SpdSpace.compositeDistance, SpdSpace.spdRho, SpdSpace.helgasonFourier, SpdSpace.HasInversion, LeanRidgelet.spdWeight, LeanRidgelet.spdSynthesis, LeanRidgelet.spdRidgelet, LeanRidgelet.spdFourierExpression, LeanRidgelet.fs_spd_reconstruction_of_inversion, LeanRidgelet.fs_spdHelgasonInversion") (uses := "fs_symmetric_inversion, fs_symmetric_reconstruction, mathlib_corner_det, mathlib_spd_model")
*Continuous horospherical SPD network (Section 5).* The symmetric positive definite matrices $`\mathbb P_m=GL(m,\mathbb R)/O(m)`, composite distance $`\langle x,u\rangle_j=\log|(u^\top xu)_j|` through the leading principal minors, $`\varrho=(-\tfrac12,\ldots,-\tfrac12,(m-1)/4)`, rank `m`. Higher rank, so the `c`-function is a product over the restricted root system. This example is now in Lean throughout: the minors the composite distance is read from together with their invariance under the nilpotent and finite factors of the Iwasawa decomposition, the chart model carrying the invariant measure $`|\det x|^{-(m+1)/2}\prod_{i\le j}\mathrm dx_{ij}`, the composite distance, the Helgason--Fourier transform, the network, the ridgelet transform, and the reconstruction formula `fs_spd_reconstruction_of_inversion` — which assumes the inversion formula for $`\mathbb P_m` *and nothing else*, that formula being the target `fs_spdHelgasonInversion`.

The article writes the same composite distance as $`\tfrac12\log\lambda` in the Cholesky diagonal, which is equivalent — the minors are the partial products $`|Y_j|=\prod_{i\le j}\lambda_i` — but takes its constants from Terras, who writes everything in the minors. Formalizing in Terras' coordinates rather than the article's therefore fixes $`\varrho` at the article's stated value instead of leaving it free, and it also removes a dependency: in the Cholesky diagonal the $`N`- and $`M`-invariance of the composite distance need uniqueness of the LDL decomposition, which Mathlib does not have, and in the minors they are elementary. $`|W|` and `c` remain parameters, pending the conversion from Terras' contour measure to Lebesgue measure on $`\mathfrak a^*`.
:::

:::theorem "fs_symmetric_reconstruction" (lean := "LeanRidgelet.fs_symmetric_reconstruction_of_inversion, LeanRidgelet.fs_symmetricFourierExpression_euclidean, LeanRidgelet.fs_fourierSlicePhase_mul_horosphericalWeight, LeanRidgelet.fs_harishChandraDensity_eq, LeanRidgelet.fs_symmetric_reconstruction_of_helgasonInversion") (uses := "fs_symmetric_network, fs_method, mathlib_helgason_inversion")
*Reconstruction formula on $`G/K` (Theorem 5.2), conditional on inversion.* The instance of the abstract scheme in which the input domain is $`G/K`, the direction space is the boundary $`\partial X`, the scale space is $`\mathfrak a^*\cong\mathbb R^r`, the weight is $`e^{\varrho\langle x,u\rangle}` and the inversion density is $`|W|^{-1}|c(\lambda)|^{-2}`. The Helgason--Fourier inversion formula is the hypothesis, entering here and only here as an explicit hypothesis of a theorem — never an axiom, a structure field or a `sorry`. Proving it, first for the hyperbolic space and the manifold of positive definite matrices, is the separate long-term milestone M10. The hypothesis was written out by hand when the theorem was stated, before the Helgason--Fourier theory existed; the last three declarations identify it with `SymmetricSpace.HasHelgasonInversion` — the layer's plane wave times its horospherical weight is the horospherical character, and the article's density is the Plancherel density — so what remains to be supplied for a concrete space is exactly the inversion formula and nothing else.
:::

The shape is inhabited: a one-point boundary with $`\varrho=0` and the identity as composite distance returns the Euclidean instance, so the conditional theorem is not vacuous in shape. The article's scalar $`\frac{|W|}{2\pi}\int\sigma^\sharp\overline{\rho^\sharp}|\omega|^{-r}` is the Fourier slice pairing with $`|W|` moved into the density of the inversion formula, where it belongs.

*Section 6: the $`d`-plane layer and pooling*

:::definition "fs_dplane_transform" (lean := "MeasureTheory.dPlaneTransform, MeasureTheory.planeOrthogonalSplit, LeanRidgelet.dPlaneCoord, LeanRidgelet.stiefelSynthesis, LeanRidgelet.sphereSynthesis, LeanRidgelet.sphereFourierExpression") (uses := "mathlib_dplane_transform")
*The $`d`-plane transform and the $`d`-plane layer.* $`P_d[f](U,\boldsymbol b)=\int_{\ker U}f(U\boldsymbol b+y)\,\mathrm dy` and $`S[\gamma](\boldsymbol x)=\int\gamma(U,\boldsymbol b)\sigma(U^\top\boldsymbol x-\boldsymbol b)`, with a multivariate activation $`\sigma:\mathbb R^k\to\mathbb C` modelling a pooling layer. The Stiefel manifold is the type of linear isometries $`\mathbb R^k\to E`, which is what an orthonormal $`k`-frame is. At codimension one that type is the unit sphere, and the layer is written over the sphere directly; the layers over the full-column-rank matrices and over the similitude group are not yet defined.
:::

:::theorem "fs_dplane_fractional" (lean := "LeanRidgelet.fs_fourier_dPlaneTransform_fractional") (uses := "fs_dplane_transform, mathlib_dplane_transform")
*Over the Stiefel manifold the ridgelet transform degenerates to a Radon transform.* If $`g` is a fractional derivative of $`f` of order $`s`, the bias spectrum of $`P_d[g](U,\cdot)` is $`\|\boldsymbol\omega\|^s\widehat f(U\boldsymbol\omega)`. The article's ansatz over the Stiefel manifold is $`\gamma^\sharp(U,\boldsymbol\omega)=\widehat f(U\boldsymbol\omega)|U\boldsymbol\omega|^{d-t}`, which is that right-hand side with $`s=d-t`, so the coefficient function the method produces is the $`d`-plane transform of a fractional derivative of the target. The fractional Laplacian is not in Mathlib, so its multiplier property is the hypothesis rather than a definition.
:::

:::lemma_ "fs_dplane_polar_codim_one" (lean := "LeanRidgelet.norm_smul_coe_sphere, LeanRidgelet.fs_matrixPolarIntegration_codim_one") (uses := "mathlib_polar_coordinates")
*The matrix polar integration formula at codimension one (Lemma C.2, $`k=1`).* $`c_{m,k}\int_{\mathbb R^m}F=\int_{V_{m,k}\times\mathbb R^k}F(U\boldsymbol b)|U\boldsymbol b|^{m-k}` becomes, at $`k=1`, the two-sided polar formula: the Stiefel manifold is the unit sphere, the weight $`|U b|^{m-1}` is $`|b|^{m-1}`, and the constant $`c_{m,1}=\int_{\mathbb S^0\times V_{m,0}}=2` is the double cover $`(b,\boldsymbol u)\mapsto b\boldsymbol u` of $`\mathbb R^m\setminus\{0\}`. So codimension one needs no measure theory on the Stiefel manifold at all, which is why it is the case within reach.
:::

:::lemma_ "fs_dplane_inversion" (lean := "LeanRidgelet.fs_dPlaneInversion") (uses := "fs_dplane_transform, mathlib_matrix_polar, fs_reconstruction_euclidean")
*Inversion of the `d`-plane transform (Lemma 6.2).* $`f(x)=(2\pi)^{-m}\int_{V_{m,k}\times\mathbb R^k}\widehat f(U\boldsymbol\omega)|U\boldsymbol\omega|^{m-k}e^{iU\boldsymbol\omega\cdot x}\,\mathrm d\boldsymbol\omega\,\mathrm dU`. The article proves this first and derives the reconstruction formulas from it; here it falls out of the same two ingredients they do — the matrix polar integration formula and Fourier inversion — so it is a corollary rather than a lemma. It is worth stating separately because it is where the constant can be compared, and the comparison finds a third difference: the printed formula has no $`c_{m,k}`, while the article's own Lemma C.2 puts one into the change of variables its proof performs. The correct form is $`f(x)=(c_{m,k}(2\pi)^m)^{-1}\int\cdots`.
:::

:::theorem "fs_dplane_stiefel_codim_one" (lean := "LeanRidgelet.fs_sphere_fourierExpression_of_bias, LeanRidgelet.fs_sphere_reconstruction_of_inversion, LeanRidgelet.fs_angularFourier_slice_radonTransform, LeanRidgelet.fs_angularFourier_radonTransform_fractional, LeanRidgelet.fs_stiefel_reconstruction_codim_one") (uses := "fs_dplane_transform, fs_dplane_polar_codim_one, fs_dplane_fractional, fs_reconstruction_euclidean")
*Reconstruction on the Stiefel manifold at codimension one (Theorem 6.3, $`k=1`).* For an activation of spectrum $`\sigma^\sharp(\omega)=|\omega|^t` and the coefficient function $`R[f](\boldsymbol u,b)=\triangle_b^{(d-t)/2}P_d[f](\boldsymbol u,b)`, $`d=m-1`, the layer over the sphere satisfies $`S[R[f]](\boldsymbol x)=c_{m,1}(2\pi)^{d}f(\boldsymbol x)`. The derivation is the master identity: Step 1 turns the layer into its Fourier expression, the separation-of-variables condition makes the integrand $`|\omega|^{m-1}\widehat f(\omega\boldsymbol u)` up to a constant, polar coordinates evaluate the direction integral against $`c_{m,1}=2`, and Fourier inversion evaluates what is left against $`(2\pi)^m`. There is no Step 2: the Stiefel case has no scale parameter to rescale.
:::

The master identity constrains only the *product* $`\gamma^\sharp(\boldsymbol u,\omega)\sigma^\sharp(\omega)`, so the activation spectrum need not be even; that is what makes the classical Radon formula an instance rather than a limiting case.

:::theorem "fs_dplane_stiefel" (lean := "LeanRidgelet.inner_dPlaneCoord, LeanRidgelet.stiefelFourierExpression, LeanRidgelet.fs_stiefel_fourierExpression_of_bias, LeanRidgelet.fs_stiefel_reconstruction_of_inversion, LeanRidgelet.fs_ae_ne_zero_frame, LeanRidgelet.fs_angularFourier_slice_dPlaneTransform, LeanRidgelet.fs_angularFourier_dPlaneTransform_fractional, LeanRidgelet.fs_stiefel_reconstruction, LeanRidgelet.fs_stiefelSynthesis_codimOne") (uses := "fs_dplane_transform, fs_dplane_stiefel_codim_one, mathlib_matrix_polar, mathlib_stiefel_codim_one, fs_reconstruction_euclidean")
*Reconstruction on the Stiefel manifold in general codimension (Theorem 6.3).* The same three moves as at codimension one, with the sphere replaced by the Stiefel manifold: Step 1 turns the layer into its Fourier expression, the separation-of-variables condition makes the integrand $`\widehat f(U\boldsymbol\omega)|U\boldsymbol\omega|^{d}` up to a constant, the *matrix* polar integration formula evaluates the frame integral, and Fourier inversion evaluates what is left. There is still no Step 2. What makes the neuron a plane wave in $`U\boldsymbol\omega` is that the coordinate map is the transpose of the frame, $`\langle\boldsymbol\omega,U^\top\boldsymbol x\rangle=\langle U\boldsymbol\omega,\boldsymbol x\rangle`.
:::

The constant is $`c_{m,k}(2\pi)^d`, the reciprocal of the one in the article, and the value of $`c_{m,k}` differs as well: the invariant measure used here is a probability measure, so it comes out as $`|\mathbb S^{k-1}|/|\mathbb S^{m-1}|`, which in the classical normalization reads $`|\mathbb S^{k-1}|\cdot\sigma_{m-1,k-1}` — the article's $`c_{m,k}` with frames of the *orthogonal complement* of the direction rather than of the whole space. The article's inversion formula for the $`d`-plane transform likewise omits a factor $`c_{m,k}`. The article's own form of the theorem — activation spectrum $`|\boldsymbol\omega|^t`, coefficient function $`R[f](U,\boldsymbol b)=\triangle_{\boldsymbol b}^{(d-t)/2}P_d[f](U,\boldsymbol b)` — is the specialization at $`c=1`, and the bias spectrum of that coefficient function is computed by the Fourier slice theorem in the angular convention together with the multiplier hypothesis standing in for the fractional Laplacian. Note that the two Fourier conventions genuinely differ here: a multiplier $`\|\xi\|^s` in the Mathlib convention is $`(2\pi)^s\|\xi\|^s` in the angular one, so the reconstruction formula needs the angular form and not the one recorded in `fs_dplane_fractional`.

The article's standing absolute-convergence assumption is not needed: the two hypotheses the matrix polar formula carries are discharged in `mathlib_matrix_polar` for a strongly measurable integrand, so the master identity asks for that instead, and the article's own form of the theorem asks for nothing beyond integrability of the target and of its Fourier transform — the Fourier transform of an integrable function being continuous, hence measurable.

That the general codimension really does specialize to codimension one is a theorem here and not a remark: at $`k=1` the two layers agree up to the total mass of the surface measure, the invariant measure on the Stiefel manifold being normalized to a probability measure and Mathlib's surface measure not. The two parameter spaces are identified by `mathlib_stiefel_codim_one`, the two bias spaces by the coordinate of $`\mathbb R^1`, and the frame coordinate by the transpose identity above.

:::theorem "fs_dplane_similitude" (lean := "LeanRidgelet.rpow_similitude_split, LeanRidgelet.rpow_similitude_radial, LeanRidgelet.similitudeSynthesis, LeanRidgelet.similitudeFourierExpression, LeanRidgelet.fs_similitude_fourierExpression_of_bias, LeanRidgelet.fs_similitude_reconstruction_of_inversion") (uses := "fs_dplane_transform, fs_dplane_stiefel, mathlib_matrix_polar")
*Reconstruction on the similitude group (Theorem 6.2).* With the weight matrix restricted to $`A=aU` and the parameter measure $`a^{m-s-1}\,\mathrm da\,\mathrm dU`, the ridgelet transform is $`R_s[f;\rho](aU,\boldsymbol b)=a^{m-s-1}\int\triangle^{s/2}[f]\overline{\rho(A^\top\boldsymbol x-\boldsymbol b)}` for any real $`s`. This extends the $`d`-plane ridgelet transforms of Donoho and of Rubin. Formalized for an arbitrary real $`s`.
:::

Unlike the Stiefel case this one has a scale, and the scale is not a passenger: it couples to the radial variable of the bias frequency through $`y=ar`. In particular the similitude network is *not* a scale mixture of Stiefel networks — at a fixed scale no power of $`\sigma^\sharp\overline{\rho^\sharp}` satisfies the Stiefel separation-of-variables condition, and that coupling is the substance of this case. The derivation is polar coordinates in the bias frequency, the one-dimensional substitution $`y=ar` in the scale, and then the direction average, whose weight $`y^{m-1}` is exactly what the substitution produces; the Fubini exchange that moves the bias frequency outside the scale integral goes into Step 1, where the article puts it.

The two exponent identities are what make the substitution come out: $`a^{m-s-1}(ar)^s=r^{-(m-s-1)}(ar)^{m-1}`, so that the exponent $`s` cancels out of the $`y`-dependence, and $`r^{k-1}\cdot r^{-(m-s-1)}\cdot r^{-1}=r^{-(d-s+1)}`, which is the weight the article's scalar $`(\!(\sigma,\rho)\!)_s` integrates the two spectra against. That scalar is written in the article's theorem statement as an integral over $`\mathbb R^k`, but what the derivation produces — and what is proved here — is the *radial* integral $`\int_{\mathbb S^{k-1}}\int_{r>0}r^{-(d-s+1)}\sigma^\sharp(rv)\overline{\rho^\sharp(rv)}\,\mathrm dr\,\mathrm dv`, the same expression *without* the Jacobian $`r^{k-1}` of polar coordinates. The article's own appendix writes the constant as a radial integral at the point where it is produced, so the $`\mathbb R^k` form of the statement is where the Jacobian slips in; the two agree at $`k=1`.

:::theorem "fs_dplane_affine" (lean := "LeanRidgelet.svdDiag, LeanRidgelet.svdDiag_apply, LeanRidgelet.svdDiag_comm, LeanRidgelet.inner_svdDiag, LeanRidgelet.fs_ae_forall_coord_ne_zero, LeanRidgelet.affineSynthesis, LeanRidgelet.affineFourierExpression, LeanRidgelet.fs_affine_fourierExpression_of_bias, LeanRidgelet.fs_affine_reconstruction_of_inversion, LeanRidgelet.fs_exists_svd_frame") (uses := "fs_dplane_transform, fs_dplane_stiefel, mathlib_diagonal_scaling, mathlib_matrix_polar, mathlib_svd")
*Reconstruction on the full-column-rank matrices (Theorem 6.1).* The densest of the three solutions, over all injective weight matrices, with the singular-value density $`\delta(A)` in the ridgelet transform. The derivation runs through the singular value decomposition $`A=UDV^\top`: the frame $`U` is a point of the Stiefel manifold, $`V` a rotation of the frequency space, and $`D` the $`k` singular values, which act on a frequency coordinatewise. Formalized in those coordinates. In the article's statement the first product in $`\delta(A)` runs to $`d`; it runs to $`k`, the number of singular values, as in the article's own appendix.
:::

**The parametrization is part of the definition.** The article's parameter measure is Lebesgue measure $`\mathrm dA` on the matrix space, and converting it to the singular value coordinates is its Lemma C.3, the Jacobian $`\mathrm dA=\delta(D)\,\mathrm dD\,\mathrm dU\,\mathrm dV`, whose published proof goes through exterior differential forms. Mathlib is far from it: it has singular *values* but not the decomposition, and neither the Jacobian of the matrix polar decomposition nor Weyl's integration formula for real symmetric matrices, which that Jacobian factors through. So the layer is defined in the singular value coordinates with the Jacobian left as a parameter.

That costs less than it appears to, for two reasons. The weight enters the separation-of-variables condition only as a factor of the coefficient function, and the article's coefficient function carries $`1/\delta(A)`, so the two cancel and the reconstruction formula holds for *every* weight. And the two layers have the same *neurons*: the decomposition itself, as opposed to its Jacobian, is `mathlib_svd`, and it gives every injective weight matrix a set of singular value coordinates with the same plane-wave frequency. So the Jacobian is needed only to relate the two parameter measures — for the reading of the theorem, not for its proof.

What the derivation does need is two changes of variables and then the matrix polar integration formula, the same one the Stiefel case ends with. The frequency is rotated by $`V`, which is an isometry hence measure preserving; the singular values are then traded for the rotated frequency coordinatewise, $`\boldsymbol y=D\boldsymbol\omega'`, whose Jacobian is $`\prod_i|\omega'_i|` — that is `mathlib_diagonal_scaling`, and it is where the $`\prod_i|\omega_i|^{-1}` of the article's scalar comes from, rather than a power of $`|\boldsymbol\omega|`. After both, the parameter integral is the weighted frame section the matrix polar formula evaluates. So the affine case is the Stiefel case with two substitutions in front of it.

The comparison of scalars gives one more difference. The article's $`(\!(\sigma,\rho)\!)` is $`\int_{\mathbb R^k}\sigma^\sharp\overline{\rho^\sharp}\prod_i|\omega_i|^{-1}`, obtained from the derivation's $`\int_{O(k)}\int_{\mathbb R^k}\sigma^\sharp(V\boldsymbol\omega')\overline{\rho^\sharp(V\boldsymbol\omega')}\prod_i|\omega'_i|^{-1}` by dropping $`\int_{O(k)}\mathrm dV` against the total mass `1`. That is legitimate only if the inner integral does not depend on $`V`, and it does: substituting $`\boldsymbol\omega=V\boldsymbol\omega'` turns the weight into $`\prod_i|(V^{-1}\boldsymbol\omega)_i|^{-1}`, which is not rotation invariant, and whose average over $`O(k)` diverges for $`k\geq2`. So the printed scalar is the derivation's integrand at $`V=1` rather than its average. Here that independence is a hypothesis, which is exactly what the article's step needs; the derivation itself is proved without it. At $`k=1` the group is $`\{\pm1\}` and the two agree.

Three deviations from the article are recorded in Section 6. The constant of the Stiefel reconstruction formula is the reciprocal of the article's: the coefficient function of the theorem has $`\rho^\sharp\equiv1`, hence auxiliary factor $`\phi^\sharp\equiv1`, whereas the quoted constant $`((2\pi)^dc_{m,k})^{-1}` is the one belonging to the normalization $`\phi^\sharp=c_{m,k}^{-1}(2\pi)^{-d}` that makes the formula reproduce $`f` exactly. The article's identification of the activation with the exponent $`t` reads off the step function at $`t=-1`, but the step function's spectrum is $`\pi\delta(\omega)+(i\omega)^{-1}`, whose homogeneous part is $`-i\,\mathrm{sgn}(\omega)|\omega|^{-1}` rather than $`|\omega|^{-1}`. And the scalar of the affine formula is an $`O(k)`-average, as above.

*Section 7: the classical Radon formula*

:::theorem "fs_fourier_formula_classical" (lean := "LeanRidgelet.fs_fourierFormula_irieFunahashi") (uses := "fs_reconstruction_euclidean")
*The Fourier formula of Irie and Funahashi (Section 7).* $`f(x)=((2\pi)^m\sigma^\sharp(1))^{-1}\int_{\mathbb R^m\times\mathbb R}\widehat f(a)\sigma(a\cdot x-b)e^{ib}\,\mathrm da\,\mathrm db`. The Fourier slice method with the bias frequency *pinned* at `1` instead of integrated over, which is why it needs no admissibility condition on the activation: there is no $`|\omega|^{-m}` to make integrable. One substitution does it — $`\int\sigma(a\cdot x-b)e^{ib}\,\mathrm db=e^{ia\cdot x}\sigma^\sharp(1)` by $`b\mapsto a\cdot x-b` — after which Fourier inversion finishes. Stated as an iterated integral, so there is no Fubini exchange either, and Fourier inversion at the point is the only hypothesis.
:::

:::theorem "fs_radon_classical" (lean := "LeanRidgelet.fs_ae_ne_zero, LeanRidgelet.fs_radon_reconstruction_codim_one") (uses := "fs_dplane_stiefel_codim_one")
*The Radon formula of Carroll--Dickinson and Ito (Theorem 7.2).* $`f(\boldsymbol x)=\frac{1}{2(2\pi)^{m-1}}\int_{\mathbb S^{m-1}\times\mathbb R}\partial_b(-\triangle_b)^{(m-1)/2}P[f](\boldsymbol u,b)\,\sigma(\boldsymbol u\cdot\boldsymbol x-b)`, for $`\sigma` the step function. This is an instance of the codimension-one master identity at the step function's actual spectrum $`(i\omega)^{-1}`, whose coefficient function accordingly carries the multiplier $`i\omega|\omega|^{m-1}` rather than $`|\omega|^m`. Its constant $`(2(2\pi)^{m-1})^{-1}` is the reciprocal of the one proved above, as it must be since the classical formula is solved for $`f`, so this is an independent confirmation of the correction to the constant of the Stiefel formula.
:::

:::theorem "fs_dplane_rubin" (uses := "fs_dplane_similitude")
*Rubin's continuous `d`-plane ridgelet transform (Theorem 7.3).* Quoted by the article from the literature, with the remark that it is the case of `fs_dplane_similitude` in which both the activation and the ridgelet function are radial — the Euclidean distance from a point to a `d`-plane being $`|U^\top\boldsymbol x-\boldsymbol b|`. Not stated in Lean: the normalization of the transform cannot be checked against its source, which is not among the reference texts of this project, and a `sorry` on a statement that cannot be checked is worth less than none.
:::

*What remains*

:::theorem "fs_target_fractional_derivative" (lean := "LeanRidgelet.dilateCLE, LeanRidgelet.fs_exists_angularFourier_eq, LeanRidgelet.angularFourierSchwartz, LeanRidgelet.contDiffAt_norm_rpow, LeanRidgelet.fs_exists_fractionalDerivative_of_compactSupport, LeanRidgelet.fs_exists_hasTemperateGrowth_eq_norm_rpow, LeanRidgelet.fs_exists_fractionalDerivative") (uses := "fs_dplane_stiefel, mathlib_temperate_growth_rpow")
*The fractional derivative exists.* Multiplying the Fourier transform of a Schwartz function by $`|\xi|^s` again comes from a Schwartz function, provided that transform vanishes near the origin. This is the one hypothesis `fs_dplane_stiefel` still carries, and discharging it is what makes the article's own form of `thm:stiefel` unconditional.

Two ingredients are general. The angular Fourier transform is *onto* the Schwartz space, because Mathlib's is invertible there and the two conventions differ by a dilation, which the Schwartz space is invariant under; so it is enough to produce the intended transform. And $`|\xi|^s` is smooth away from the origin, which is where the hypothesis on the transform's support does its work.

**The band-limited case is proved outright.** If the transform is in addition compactly supported — that is, if the target is band-limited to an annulus — the product is smooth by gluing, being smooth off the origin and identically zero on the ball, it inherits the compact support, and a smooth compactly supported function is Schwartz. No multiplier theory is needed.

**The general case is proved too.** What it needs is a function of temperate growth agreeing with $`|\xi|^s` outside a ball, and the way to get one is to correct the multiplier *inside* the ball, where it is not needed: $`|\xi|^s` itself is not of temperate growth — for non-even `s` it is not smooth at the origin, and for negative `s` not even bounded there — but $`(\|\xi\|^2+r^2\beta(\xi))^{s/2}`, with $`\beta` a bump equal to `1` near the origin and supported in the ball of radius `r`, is: the inner function is a norm square plus a smooth compactly supported function, hence temperate and bounded away from zero, and it equals $`\|\xi\|^2` outside the ball.

That last step is `mathlib_temperate_growth_rpow`, and it is where the Japanese bracket comes in. The bracket is *not* a substitute for $`|\xi|^s`: $`(1+|\xi|^2)^{s/2}` is the Bessel potential multiplier $`(1-\triangle)^{s/2}` whereas $`|\xi|^s` is the Riesz one $`(-\triangle)^{s/2}`, and Section 6 needs the homogeneous one — the separation-of-variables condition asks the product $`\gamma^\sharp\sigma^\sharp` to be $`\widehat f(U\boldsymbol\omega)|U\boldsymbol\omega|^d`, and it is exactly that homogeneity which matches the weight $`|U\boldsymbol b|^{m-k}` of the matrix polar formula. But Mathlib's temperate growth *of the bracket* is the right proof, because there the inner function already avoids the origin; generalizing it to an arbitrary inner function bounded away from zero is what lets the inner function be chosen as above.
:::

:::lemma_ "fs_target_svd_jacobian" (lean := "LeanRidgelet.svdChart, LeanRidgelet.svdMatrix, LeanRidgelet.svdJacobian, LeanRidgelet.fs_svdJacobian") (uses := "fs_dplane_affine, mathlib_svd")
*The Jacobian of the singular value decomposition (Lemma C.3).* $`\mathrm dA=\delta(D)\,\mathrm dD\,\mathrm dU\,\mathrm dV` with $`\delta(D)=2^{-k}|\det D|^{m-k}\prod_{i<j}(d_i^2-d_j^2)`. Stated with a `sorry`, for the lower Lebesgue integral so that no convergence hypothesis is needed, and with the constant left existential — the invariant measures used here are normalized to probability measures whereas the article's are the classical ones, so the statement should not fix it. **No proof in this development depends on it**: the reconstruction formula over full-column-rank matrices is proved in the singular value coordinates, and `mathlib_svd` shows those coordinates reach every such matrix, so what is missing is only the relation between the two parameter *measures*. Determining the constant is what would settle the two open questions about the article's constants — whether $`c_{m,k}` is a Stiefel manifold of the orthogonal complement of the direction, and whether dropping the ordering of the singular values costs a $`k!`.
:::
