import LeanRidgeletBlueprint.Chapters.ToMathlibInvariantGeometry
import LeanRidgelet.ToMathlib.LieGroup.Symmetric
import LeanRidgelet.ToMathlib.LieGroup.Hyperbolic
import LeanRidgelet.ToMathlib.LieGroup.PositiveDefinite
import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false
-- Verso directive headers and display mathematics must stay on one physical line.
set_option linter.style.longLine false
set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Mathlib candidates: symmetric spaces and the Helgason--Fourier transform" =>
%%%
file := "symmetric-spaces"
%%%

The Helgason--Fourier transform on a noncompact symmetric space `X = G/K`: an abstract layer that carries the geometry — the composite distance, the constant `ϱ`, the invariant and boundary measures, and the Harish-Chandra `c`-function — as data, so that the inversion formula is a definite proposition rather than an axiom; and the two concrete models the layer is instantiated at, the Poincaré ball model of real hyperbolic space and the manifold of positive definite matrices in Terras' coordinates.

*The abstract layer, with the geometry as data*

:::theorem "mathlib_symmetric_space_defs" (lean := "SymmetricSpace.horosphericalCharacter, SymmetricSpace.horosphericalCharacter_zero_right, SymmetricSpace.horosphericalCharacter_zero_rho, SymmetricSpace.norm_horosphericalCharacter, SymmetricSpace.horosphericalCharacter_ne_zero, SymmetricSpace.horosphericalCharacter_add, SymmetricSpace.horosphericalCharacter_eq, SymmetricSpace.horosphericalCharacter_neg, SymmetricSpace.helgasonFourier, SymmetricSpace.sphericalFunction, SymmetricSpace.helgasonInversionIntegral, SymmetricSpace.helgasonFourier_zero, SymmetricSpace.helgasonFourier_const_mul, SymmetricSpace.sphericalFunction_eq_one, SymmetricSpace.integral_helgasonFourier_eq")
*The Helgason--Fourier transform, with the geometry as data.* On a noncompact symmetric space $`X=G/K` the plane wave $`e^{-i\langle\lambda,x\rangle}` of $`\mathbb R^m` is replaced by $`e^{(-i\lambda+\varrho)(A(x,b))}`, where $`A(x,b)\in\mathfrak a\cong\mathbb R^r` is the composite distance from the origin to the horosphere through `x` with normal $`b\in B=K/M`, and $`\varrho` is the half-sum of the positive restricted roots. Mathlib has none of the group theory behind this — no Iwasawa decomposition, no spherical functions, no Harish-Chandra `c`-function — so the composite distance and $`\varrho` enter as *data*, and the identities the geometry does satisfy stay hypotheses of the theorems that need them rather than fields of a structure.
:::

Everything is built from one function, the character $`v\mapsto e^{(i\lambda+\varrho)(v)}` of $`\mathfrak a`. It is the exponential of a linear functional, hence *multiplicative* in `v`; that single fact is what turns the cocycle relation for `A` into a product formula for the kernels, and it is why $`\varrho=0` returns the Euclidean plane wave while $`\lambda=0` returns the weight $`e^{\varrho(v)}` that a layer of a network on `G/K` carries. Its modulus is $`e^{\varrho(v)}`, so the growth of the kernel is governed by $`\varrho` alone, uniformly in the frequency.

The one theorem here is the measure-theoretic core of Helgason's remark that the transform *extends* the spherical transform: averaging $`\hat f(\lambda,b)` over the boundary pairs `f` against the spherical function $`\varphi_{-\lambda}`. When `f` is `K`-invariant its transform does not depend on `b`, so the left side is the transform itself and the right side is the spherical transform. The proof is Fubini, so the joint integrability hypothesis is the whole of it.

:::theorem "mathlib_symmetric_cocycle" (lean := "SymmetricSpace.IsCompositeCocycle, SymmetricSpace.isCompositeCocycle_id, SymmetricSpace.IsCompositeCocycle.comp, SymmetricSpace.IsCompositeCocycle.helgasonFourier_apply, SymmetricSpace.IsCompositeCocycle.norm_helgasonFourier_apply, SymmetricSpace.IsCompositeCocycle.sphericalFunction_apply, SymmetricSpace.IsCompositeCocycle.sphericalFunction_apply_of_shift_eq_zero") (uses := "mathlib_symmetric_space_defs")
*The transformation law of the composite distance, and what it does to the transform.* $`A(g\cdot x,g\cdot b)=A(x,b)+A(g\cdot o,g\cdot b)`: moving both arguments by the same element of `G` shifts the composite distance by a quantity depending on the boundary point alone. Abstractly this is the predicate `IsCompositeCocycle T S A shift`; under it, and with `T` preserving the measure of `X`, the Helgason--Fourier transform at the moved boundary point is the transform of the moved function times the character at the shift.
:::

The displacement is read at $`S_1b` and not at `b` when two motions are composed, which is what makes this a cocycle rather than a homomorphism, and it is the whole of the bookkeeping. Everything else follows from the multiplicativity of the character: the shift leaves the integral over `X` as a constant factor, so the modulus of the transform picks up exactly $`e^{\varrho(\text{shift})}` and nothing depending on the frequency.

The spherical function does not simplify as cleanly, and the statement here says so rather than pretending otherwise. Its boundary integral acquires a factor $`e^{(i\lambda+\varrho)(\text{shift}(b))}` that depends on `b`, so it cannot be pulled out; what does come out is the genuine invariance $`\varphi_\lambda(T x)=\varphi_\lambda(x)`, and only when the shift vanishes — the case of a motion fixing the base point, that is of an element of `K`, which is the classical statement that spherical functions are `K`-invariant.

:::theorem "mathlib_horocycle_radon" (lean := "SymmetricSpace.horocycleRadon, SymmetricSpace.dualHorocycle, SymmetricSpace.sphericalFunction_eq_dualHorocycle, SymmetricSpace.helgasonFourier_eq_integral_horocycleRadon, SymmetricSpace.helgasonFourier_eq_fourier_weightedHorocycleRadon, SymmetricSpace.helgasonInversionIntegral_eq_integral_dualHorocycle") (uses := "mathlib_symmetric_space_defs")
*The Fourier slice theorem on a symmetric space.* On $`\mathbb R^m` the Fourier transform is the one-dimensional Fourier transform of the Radon transform. Helgason opens Ch. III of *Geometric Analysis on Symmetric Spaces* by observing that the same holds on $`X=G/K` with *horospheres* in place of hyperplanes, and that is proved here: $`\hat f(\lambda,b)=\int_{\mathfrak a}e^{(-i\lambda+\varrho)(t)}Rf(b,t)\,\mathrm dt`, where $`Rf(b,t)` is the integral of `f` over the horosphere at composite distance `t` with normal `b`.
:::

The horospheres with a fixed normal are the level sets of the composite distance, so a horosphere integral is a fibre integral. Mathlib has no Riemannian measure to build one from, and on a general `X` there is no reason for one to exist, so the family of fibre measures is *data*: a kernel carried by the horosphere, plus the hypothesis that integrating against the invariant measure is integrating over a fibre and then over $`\mathfrak a`. In a concrete model that hypothesis is the horospherical change of variables, and it is where the normalization of $`\mathrm dt` is fixed — which is where the constant of the inversion formula comes from, so it is better in the open than buried in a definition. Given the kernel the proof is one rewriting: on a fibre the kernel $`e^{(-i\lambda+\varrho)(A(x,b))}` is the *constant* $`e^{(-i\lambda+\varrho)(t)}`, so it leaves the fibre integral.

Splitting the character into its phase and its weight puts the right-hand side in the form of a genuine Euclidean Fourier transform, of $`t\mapsto e^{\varrho(t)}Rf(b,t)`. That is the reason the inversion formula on `X` decomposes into a Euclidean Fourier inversion and an inversion of the Radon transform, and the reason the density $`|c(\lambda)|^{-2}` appears as a Fourier multiplier rather than as a geometric factor. The dual transform is recorded alongside, together with two identifications it makes: the spherical function is the dual transform of the character, and the inversion integral is an $`\mathfrak a`-integral of dual transforms — the shape $`f=w^{-1}(\Lambda\Lambda f^\wedge)^\vee` of Helgason's inversion of the Radon transform.

:::theorem "mathlib_helgason_inversion" (lean := "SymmetricSpace.plancherelDensity, SymmetricSpace.plancherelDensity_eq, SymmetricSpace.plancherelDensity_pos, SymmetricSpace.plancherelDensity_congr, SymmetricSpace.cFunctionIntegral, SymmetricSpace.mul_neg_eq_normSq_of_conj, SymmetricSpace.HasHelgasonInversion, SymmetricSpace.hasHelgasonInversion_iff, SymmetricSpace.hasHelgasonInversion_of_spherical") (uses := "mathlib_symmetric_space_defs, mathlib_horocycle_radon")
*The `c`-function, the Plancherel density, and the inversion formula as a proposition.* The inversion formula $`f=|W|^{-1}\int_{\mathfrak a^*\times B}\hat f(\lambda,b)e^{(i\lambda+\varrho)(A(x,b))}|c(\lambda)|^{-2}` is stated here as a predicate on the data — never an axiom, a structure field or a `sorry` — so that a concrete model has a definite statement to prove. With the geometry left free it is not even a well-posed claim.
:::

The `c`-function is taken to be the integral $`c(\lambda)=\int_{\bar N}e^{-(i\lambda+\varrho)(H(\bar n))}\,\mathrm d\bar n`, not the Gindikin--Karpelevich product of Gamma factors, which is a *theorem* about that integral. The reason is normalization. Helgason normalizes `c` so that $`c(-i\varrho)=1` in the introduction to *Groups and Geometric Analysis*, and writes the inversion formula of *Geometric Analysis on Symmetric Spaces* Ch. III Thm 1.3 against a measure $`\mathrm d\lambda` on $`\mathfrak a^*` that is not Lebesgue measure; put together with Lebesgue $`\mathrm d\lambda` the two disagree by a power of $`\pi`. Keeping $`\mathrm d\bar n` visible forces the constant to come out of a proof instead of being copied. Only the modulus of `c` ever enters, and changing `c` without changing its modulus does not change the density — so a discrepancy in a power of $`\pi` cannot be a phase convention and must be a normalization of the measures.

The last declaration is the shape of Helgason's proof, and its value is that it says which input is deep. The inversion formula follows from two hypotheses: that the boundary integral is the convolution $`f\times\varphi_\lambda` with the spherical function, which is Lemma 1.2 of Ch. III §1 and rests on the symmetry of the spherical function — a cocycle computation, nontrivial but formal; and Harish-Chandra's inversion formula for the *spherical* transform, which is the genuinely deep analytic fact. Neither hypothesis mentions a group, which is why the reduction can be stated before any of the Lie theory exists.

*The Poincaré ball model of real hyperbolic space*

:::theorem "mathlib_hyperbolic_ball" (lean := "HyperbolicSpace.poincareBall, HyperbolicSpace.idealBoundary, HyperbolicSpace.mem_poincareBall_iff, HyperbolicSpace.mem_idealBoundary_iff, HyperbolicSpace.poissonKernel, HyperbolicSpace.compositeDistance, HyperbolicSpace.rho, HyperbolicSpace.ne_of_mem_ball_of_mem_sphere, HyperbolicSpace.one_sub_norm_sq_pos, HyperbolicSpace.poissonKernel_pos, HyperbolicSpace.poissonKernel_origin, HyperbolicSpace.compositeDistance_origin, HyperbolicSpace.exp_compositeDistance, HyperbolicSpace.volumeDensity, HyperbolicSpace.volumeDensity_pos, HyperbolicSpace.invariantMeasure") (uses := "mathlib_symmetric_space_defs")
*The Poincaré ball model of real hyperbolic space.* Mathlib has the upper half plane with its hyperbolic metric, but only in dimension two, and no hyperbolic space of general dimension. The rank-one noncompact symmetric space $`\mathbb H^m=SO^+(1,m)/O(m)` is built here in the ball model, with the composite distance $`\langle x,u\rangle=\log\bigl((1-\|x\|^2)/\|x-u\|^2\bigr)` and $`\varrho=(m-1)/2`.
:::

No Riemannian geometry is used, and none is available: Mathlib's manifold library has neither a volume measure nor a Laplace--Beltrami operator. The invariant measure is therefore *defined* as the weighted Lebesgue measure $`(2/(1-\|x\|^2))^m\,\mathrm dx` on the open unit ball, and its agreement with the Riemannian volume of the metric $`4(1-\|x\|^2)^{-2}\sum\mathrm dx_i\otimes\mathrm dx_i` is a remark rather than a dependency. In the ball model the origin lies on every horosphere through it, so $`\langle 0,u\rangle=0` at every boundary point — that normalization is what makes $`e^{(-i\lambda+\varrho)\langle x,u\rangle}` the analogue of a plane wave based at the origin.

:::theorem "mathlib_hyperbolic_mobius" (lean := "HyperbolicSpace.mobiusBracketSq, HyperbolicSpace.mobiusBracketSq_zero_right, HyperbolicSpace.mobiusBracketSq_zero_left, HyperbolicSpace.mobiusBracketSq_of_norm_eq_one, HyperbolicSpace.one_sub_mul_sq_le_mobiusBracketSq, HyperbolicSpace.mobiusBracketSq_pos, HyperbolicSpace.mobiusBracketSq_ne_zero, HyperbolicSpace.mobiusNum, HyperbolicSpace.mobius, HyperbolicSpace.mobius_self, HyperbolicSpace.mobius_zero_left, HyperbolicSpace.mobius_zero_right, HyperbolicSpace.mobiusNum_key, HyperbolicSpace.norm_sq_mobiusNum, HyperbolicSpace.norm_sq_mobius, HyperbolicSpace.one_sub_norm_sq_mobius, HyperbolicSpace.norm_mobius_lt_one, HyperbolicSpace.norm_mobius_eq_one, HyperbolicSpace.norm_sq_mobius_sub, HyperbolicSpace.poissonKernel_mobius, HyperbolicSpace.compositeDistance_mobius") (uses := "mathlib_hyperbolic_ball")
*Möbius transformations of the ball, and the cocycle of the composite distance.* The isometries of $`\mathbb H^m` that move the origin are the Möbius transformations. With Ahlfors' bracket $`[x,a]^2=1-2\langle x,a\rangle+\|x\|^2\|a\|^2` and $`\varphi_a(x)=\bigl((1-\|a\|^2)(x-a)-\|x-a\|^2a\bigr)/[x,a]^2`, everything in this node follows from *one* polynomial identity, and the last declaration is the cocycle $`\langle\varphi_a x,\varphi_a u\rangle=\langle x,u\rangle-\langle a,u\rangle` that the abstract layer asks a model to supply.
:::

The identity is this. Writing $`N_x` for the numerator of $`\varphi_a(x)`,
$$`[y,a]^2\|x-a\|^2+[x,a]^2\|y-a\|^2-2\langle N_x,N_y\rangle=(1-\|a\|^2)^2\|x-y\|^2,`
which is a polynomial identity in the six scalars $`\langle x,y\rangle`, $`\langle x,a\rangle`, $`\langle y,a\rangle`, $`\|x\|^2`, $`\|y\|^2`, $`\|a\|^2` — so `ring` proves it once the inner products are expanded, with no geometry entering at all. Everything else is division. On the diagonal it gives $`\|\varphi_a(x)\|^2=\|x-a\|^2/[x,a]^2` and hence $`1-\|\varphi_a(x)\|^2=(1-\|a\|^2)(1-\|x\|^2)/[x,a]^2`, from which the ball and its boundary sphere are preserved. Off the diagonal it gives the *conformal distortion* $`\|\varphi_a(x)-\varphi_a(y)\|^2=(1-\|a\|^2)^2\|x-y\|^2/([x,a]^2[y,a]^2)`, in which the two points enter only through their brackets. Dividing the two, and using that on the boundary the bracket is the squared Euclidean distance, gives $`P(\varphi_a x,\varphi_a u)=P(x,u)/P(a,u)` — the cocycle, once logarithms are taken.

Positivity of the bracket is not a computation either: Cauchy--Schwarz gives $`(1-\|x\|\|a\|)^2\le[x,a]^2`, which is positive as soon as $`\|x\|\le 1` and $`\|a\|<1`, so the closed ball is covered and the boundary needs no separate argument.

What is *not* here is invariance of the volume measure, which needs the Jacobian and hence the derivative of $`\varphi_a`. The conformal distortion identity is the statement that will be read off: a map whose difference quotients are a fixed scalar times an isometry has derivative a scalar times an isometry, and such a derivative has determinant of modulus $`\lambda^m` — exactly the factor the density $`(2/(1-\|x\|^2))^m` needs in order to be invariant.

:::theorem "mathlib_hyperbolic_mobius_measure" (lean := "HyperbolicSpace.mobiusInvol, HyperbolicSpace.mobiusInvol_eq, HyperbolicSpace.mobiusBracketSq_eq_add, HyperbolicSpace.mobiusInvol_sub_self, HyperbolicSpace.norm_sq_mobiusInvol_sub_self, HyperbolicSpace.mobiusBracketSq_mobiusInvol, HyperbolicSpace.mobiusInvol_mobiusInvol, HyperbolicSpace.injOn_mobius, HyperbolicSpace.image_mobius, HyperbolicSpace.differentiable_mobiusBracketSq, HyperbolicSpace.differentiable_mobiusNum, HyperbolicSpace.differentiableAt_mobius, HyperbolicSpace.mobiusFactor, HyperbolicSpace.mobiusFactor_pos, HyperbolicSpace.norm_sq_mobius_sub_eq_mul, HyperbolicSpace.norm_fderiv_mobius_apply, HyperbolicSpace.isConformalMap_fderiv_mobius, HyperbolicSpace.abs_det_fderiv_mobius, HyperbolicSpace.mobiusFactor_pow_mul_volumeDensity_mobius, HyperbolicSpace.measurable_mobius, HyperbolicSpace.lintegral_invariantMeasure_comp_mobius") (uses := "mathlib_hyperbolic_mobius")
*The invariant measure of hyperbolic space is Möbius invariant.* The measure $`(2/(1-\|x\|^2))^m\,\mathrm dx` on the unit ball is preserved by every $`\varphi_a`. This completes the geometry of the model: the isometry group acts on `ℍ^m` preserving both the measure and, by the cocycle, the Helgason--Fourier kernel.
:::

*The derivative of $`\varphi_a` is never computed.* Differentiating a rational map of a vector and evaluating a determinant would be a long calculation; the conformal distortion identity already contains the answer. Writing $`\lambda(x)=(1-\|a\|^2)/[x,a]^2`, the identity reads $`\|\varphi_a(x)-\varphi_a(y)\|^2=\lambda(x)\lambda(y)\|x-y\|^2`, so the slope of $`\varphi_a` along a line through `x` in direction `v` has squared norm $`\lambda(x)\lambda(x+tv)\|v\|^2` for every small $`t\ne 0`; letting $`t\to 0` gives $`\|D\varphi_a(x)v\|=\lambda(x)\|v\|` whatever the derivative is. By polarization the derivative then scales inner products by $`\lambda(x)^2`, so it is *conformal*, so it is $`\lambda(x)` times a linear isometry, so $`|\det|=\lambda(x)^m` — using that a linear isometry has `normDet` one and that scaling multiplies `normDet` by a power of the modulus. Only differentiability is taken from calculus.

Surjectivity onto the ball is the other input, and it comes from the involution $`\sigma_a=-\varphi_a`, which swaps `0` and `a`. Proving $`\sigma_a\circ\sigma_a=\mathrm{id}` by brute force would mean normalizing a large rational expression; instead it factors through three identities that are each one `ring`: $`\sigma_a(x)-a=-\lambda(x)(x-\|x\|^2a)`, then $`\|\sigma_a(x)-a\|^2=\lambda(x)^2[x,a]^2\|x\|^2` in the form $`(1-\|a\|^2)^2\|x\|^2/[x,a]^2`, and then $`[\sigma_a(x),a]^2=(1-\|a\|^2)^2/[x,a]^2`. Substituting the three makes every bracket cancel. Injectivity is then free, an involution being injective. The third identity is where the general relation $`[y,a]^2=\|y-a\|^2+(1-\|y\|^2)(1-\|a\|^2)` between the bracket and the Poisson kernel is used.

With the Jacobian and the bijection the invariance is the change of variables of `MeasureTheory.lintegral_image_eq_lintegral_abs_det_fderiv_mul`, and the density cancels the Jacobian pointwise: $`\lambda(x)^m(2/(1-\|\varphi_a(x)\|^2))^m=(2/(1-\|x\|^2))^m`, because $`1-\|\varphi_a(x)\|^2=(1-\|a\|^2)(1-\|x\|^2)/[x,a]^2`. That is the same identity which made $`\varphi_a` preserve the ball, so the invariance of the measure and the preservation of the ball are two readings of one computation.

:::theorem "mathlib_hyperbolic_helgason_fourier" (lean := "HyperbolicSpace.boundaryMeasure, HyperbolicSpace.instIsProbabilityMeasureBoundaryMeasure, HyperbolicSpace.boundaryMeasure_eq_sphereOrbitMeasure, HyperbolicSpace.boundaryDistance, HyperbolicSpace.boundaryDistance_origin, HyperbolicSpace.norm_horosphericalCharacter_compositeDistance, HyperbolicSpace.horosphericalCharacter_compositeDistance_mobius, HyperbolicSpace.helgasonFourier, HyperbolicSpace.helgasonFourier_eq, HyperbolicSpace.HasInversion, HyperbolicSpace.hasInversion_iff") (uses := "mathlib_hyperbolic_ball, mathlib_hyperbolic_mobius, mathlib_helgason_inversion, mathlib_sphere_invariant_measure")
*The Helgason--Fourier transform on hyperbolic space, and its inversion formula as a proposition.* Feeding the ball model to the abstract layer turns the inversion formula from a schema into a *definite claim about a definite space*, which is what was missing while no model existed: `HasInversion` is a proposition one can be asked to prove.
:::

The four pieces of data are all available. The space is the ambient Euclidean space carrying the invariant measure, which is concentrated on the ball — using the whole space rather than the ball as a subtype costs nothing and keeps every construction on a plain Euclidean space. The rank is one, so the frequency is a real number and $`\mathrm d\lambda` is Lebesgue measure on $`\mathbb R`; fixing it to be Lebesgue is deliberate, since Helgason writes the formula against a different normalization and that is exactly where the powers of $`\pi` in the constant live. The boundary is the unit sphere with the normalized surface measure, and that normalization is not a choice: by the uniqueness theorem it is the orbit measure of any unit vector, hence *the* rotation-invariant probability measure. The Plancherel density keeps $`|W|` and `c` as arguments, because pinning them down for $`\mathbb H^m` is a normalization question to be settled by proof rather than by quotation.

One identity is worth naming on its own: the modulus of the Helgason--Fourier kernel is a real power of the Poisson kernel, $`|e^{(i\lambda+t)\langle x,u\rangle}|=P(x,u)^t`, with no dependence on the frequency. At $`t=\varrho` this is the weight a layer of a network on $`\mathbb H^m` carries, so that weight is $`P(x,u)^{(m-1)/2}` — the square root of the Euclidean Poisson kernel when $`m=2`, and in general the half-density that makes the transform an isometry rather than an input-dependent coefficient.

*The manifold of positive definite matrices*

:::theorem "mathlib_hyperbolic_boundary_mobius" (lean := "HyperbolicSpace.mobiusFactor_eq_poissonKernel, HyperbolicSpace.norm_sq_mobius_sub_of_mem_sphere, HyperbolicSpace.boundaryMobius, HyperbolicSpace.coe_boundaryMobius, HyperbolicSpace.boundaryMobiusSymm, HyperbolicSpace.coe_boundaryMobiusSymm, HyperbolicSpace.boundaryMobiusSymm_boundaryMobius, HyperbolicSpace.boundaryMobius_boundaryMobiusSymm, HyperbolicSpace.boundaryMobiusEquiv, HyperbolicSpace.coe_boundaryMobiusEquiv, HyperbolicSpace.injective_boundaryMobius, HyperbolicSpace.surjective_boundaryMobius, HyperbolicSpace.bijective_boundaryMobius, HyperbolicSpace.dist_boundaryMobius, HyperbolicSpace.continuous_boundaryMobius, HyperbolicSpace.continuous_boundaryMobiusSymm, HyperbolicSpace.boundaryMobiusHomeomorph, HyperbolicSpace.boundaryDistance_coe_self, HyperbolicSpace.boundaryDistance_mobius") (uses := "mathlib_hyperbolic_mobius_measure, mathlib_hyperbolic_helgason_fourier")
*The Möbius transformation restricted to the ideal boundary is a conformal homeomorphism of the sphere whose multiplier is the Poisson kernel.* $`\operatorname{dist}(\partial\varphi_a u,\partial\varphi_a v)=\sqrt{P(a,u)P(a,v)}\operatorname{dist}(u,v)`, so the chordal distance is multiplied by the geometric mean of the multiplier at the two endpoints. The inverse is the boundary restriction of the involution $`\sigma_a=-\varphi_a`.
:::

One rewriting is the whole content. On the boundary Ahlfors' bracket is the squared Euclidean distance, $`[u,a]^2=\|u-a\|^2`, so the conformal factor $`\lambda_a(x)=(1-\|a\|^2)/[x,a]^2` restricted to the boundary *is* the Poisson kernel $`P(a,u)`. Substituting that into the conformal distortion identity already proved for the ball gives the multiplier form, and no derivative along the sphere is taken — the statement needs none. The negation in the inverse is not decoration: $`\varphi_a` is not an involution, only $`\sigma_a` is.

The transformation law of the composite distance is recorded here as a plain lemma with the hypothesis $`\|x\|<1`, and *not* as an instance of `mathlib_symmetric_cocycle`, because as an instance it would be false rather than merely unproved. The abstract predicate quantifies over every point of the ambient space, and the composite distance of the ball model carries a junk value outside the ball: at a boundary point read against itself the Poisson kernel is $`0/0`, so both sides of the law vanish and the law would force $`\langle a,u\rangle=0` at every boundary point. That already fails at $`u=a/\|a\|`, where $`P(a,u)=(1+\|a\|)/(1-\|a\|)`. The honest instance is on the subtype, and saying so is worth more than producing one.

What is *not* here is the measure-theoretic step, $`\mathrm d(\partial\varphi_a u)=P(a,u)^{m-1}\mathrm du` — that a conformal self-map of the sphere scales the surface measure by the $`(m-1)`st power of its multiplier — which is what the quasi-invariance of the boundary measure needs on top of the above. The gap is in Mathlib and not in these identities: there is no change-of-variables formula for a Hausdorff measure on a submanifold, the boundary measure is built from the polar decomposition of Lebesgue measure and carries no transformation law under a map of the sphere, and the ambient change-of-variables theorem is useless because the sphere is null for the ambient measure.

:::theorem "mathlib_cholesky_diag" (lean := "Matrix.choleskyDiag, Matrix.choleskyDiag_eq, Matrix.posDef_ldlDiag, Matrix.choleskyDiag_pos, Matrix.cholesky_conj_diag, Matrix.choleskyDiagTotal, Matrix.choleskyDiagTotal_of_posDef, Matrix.choleskyDiagTotal_of_not_posDef, Matrix.choleskyDiagTotal_pos, Matrix.choleskyDiagTotal_ne_zero") (uses := "mathlib_symmetric_space_defs")
*The Cholesky diagonal of a positive definite real matrix is positive.* On the higher-rank symmetric space $`\mathbb P_m=GL(m,\mathbb R)/O(m)` the Iwasawa decomposition *is* the Cholesky decomposition $`x=\nu\lambda\nu^\top` with $`\nu` unit lower triangular and $`\lambda` positive diagonal. Mathlib already has the decomposition, as the LDL decomposition built by Gram--Schmidt; what the symmetric-space theory needs on top of it is that the diagonal factor is positive, so that its logarithm is defined.
:::

That is not a computation: the diagonal factor is the conjugate of the matrix by the invertible Gram--Schmidt factor, conjugation by an invertible matrix preserves positive definiteness, and a positive definite matrix has positive diagonal entries. Restating the decomposition over $`\mathbb R`, where the conjugate transpose is the transpose, then gives the Iwasawa factorization in the form harmonic analysis on $`\mathbb P_m` consumes. A *total* form, junk `1` off the positive definite cone, lets the diagonal be named inside a definition without carrying a positivity proof.

The article being formalized writes the composite distance of $`\mathbb P_m` as $`\tfrac12\log\lambda` in this diagonal. The model below does not: it uses the leading principal minors instead, for the reason recorded in the next statement. The Cholesky diagonal remains what the minors are *computed from*, and the two are the same data.

:::theorem "mathlib_corner_det" (lean := "Matrix.cornerEmb, Matrix.coe_cornerEmb, Matrix.cornerEmb_injective, Matrix.cornerDet, Matrix.posDef_submatrix_cornerEmb, Matrix.cornerDet_pos, Matrix.cornerDetTotal, Matrix.cornerDetTotal_of_posDef, Matrix.cornerDetTotal_of_not_posDef, Matrix.cornerDetTotal_pos, Matrix.cornerDetTotal_ne_zero, Matrix.submatrix_cornerEmb_mul_of_lowerTriangular, Matrix.submatrix_cornerEmb_mul_transpose_of_lowerTriangular, Matrix.submatrix_cornerEmb_conj_of_lowerTriangular, Matrix.blockTriangular_submatrix_cornerEmb, Matrix.det_submatrix_cornerEmb_of_lowerTriangular, Matrix.cornerDet_conj_of_lowerTriangular_unit, Matrix.cornerDet_conj_diagonal_sign, Matrix.diagonal_sign_mul_self, Matrix.isUnit_diagonal_sign, Matrix.posDef_conj_diagonal_sign_iff, Matrix.cornerDetTotal_conj_diagonal_sign, Matrix.cornerDet_of_ldl") (uses := "mathlib_cholesky_diag")
*The leading principal minors of a positive definite matrix, and their invariance under the nilpotent and finite factors of the Iwasawa decomposition.* For lower triangular $`L` the corner of a conjugate is the conjugate of the corner, $`(LYL^\top)_j=L_jY_jL_j^\top`; hence $`|(LYL^\top)_j|=|Y_j|` when $`L` has unit diagonal, and likewise when $`L` is a $`\pm1` diagonal matrix. The dictionary to the Cholesky diagonal is $`|Y_j|=\prod_{i\le j}\lambda_i`.
:::

Terras writes harmonic analysis on $`\mathbb P_m` in terms of the *power function* $`p_s(Y)=\prod_j|Y_j|^{s_j}` over the upper-left corners $`Y_j`, so in her coordinates the composite distance is the vector $`j\mapsto\log|Y_j|` and the horospherical character is $`p_s` on the nose. That is the reason to prefer the minors to the Cholesky diagonal, and it is not only bookkeeping. The composite distance has to be $`N`-invariant, horospheres being $`N`-orbits, and $`M`-invariant, the boundary being $`K/M` rather than $`K`. Stated in the Cholesky diagonal, both facts need *uniqueness* of the LDL decomposition, which Mathlib does not have and which is a real piece of work. Stated in the minors they are elementary, and the whole of their content is the displayed identity above — which holds because the first $`j` rows of a lower triangular matrix are supported in the first $`j` columns, and because $`\det L_j=1` for a unitriangular $`L` and $`(\det L_j)^2=1` for a sign matrix.

So the choice of coordinates removes a dependency rather than merely relabelling one. It is also what lets Terras' constants be used verbatim, as the next statement records.

:::theorem "mathlib_spd_model" (lean := "Matrix.posDef_transpose_mul_mul, SpdSpace.UpperIdx, SpdSpace.ofUpper, SpdSpace.ofUpper_apply_of_le, SpdSpace.ofUpper_apply_of_not_le, SpdSpace.ofUpper_isSymm, SpdSpace.measurable_ofUpper_apply, SpdSpace.chart, SpdSpace.invariantDensity, SpdSpace.invariantMeasure, SpdSpace.act, SpdSpace.act_one, SpdSpace.isSymm_act, SpdSpace.posDef_act, SpdSpace.Boundary, SpdSpace.boundaryMatrix, SpdSpace.compositeDistance, SpdSpace.compositeDistance_apply, SpdSpace.spdRho, SpdSpace.helgasonFourier, SpdSpace.helgasonFourier_eq, SpdSpace.HasInversion, SpdSpace.hasInversion_iff") (uses := "mathlib_corner_det, mathlib_helgason_inversion, mathlib_orthogonal_group")
*The manifold of positive definite matrices, and its Helgason--Fourier inversion formula as a proposition.* $`\mathbb P_m=GL(m,\mathbb R)/O(m)` is the higher-rank example of Section 5 — the rank is `m`, against one for hyperbolic space whatever its dimension. Supplying its geometry to the abstract layer makes the inversion formula on it a definite claim.
:::

Two arrangements make the article's measure $`|\det x|^{-(m+1)/2}\prod_{i\le j}\mathrm dx_{ij}` into a measure, and both follow the precedent of the hyperbolic ball rather than building manifold theory. *The carrier*: that formula integrates over the $`m(m+1)/2` independent entries of a symmetric matrix, so restricting Lebesgue measure of the full matrix space to the symmetric matrices would give zero. So $`\mathbb P_m` is modelled by the *chart* of upper-triangular coordinates, on which Lebesgue measure *is* $`\prod_{i\le j}\mathrm dx_{ij}` — the same device as the singular-value chart of the `d`-plane development, and one that also sidesteps a gap, Mathlib giving `Matrix` neither an inner product nor a measurable space. *The positivity*: the measure is concentrated on the positive definite cone by restricting to the preimage of $`\mathbb P_m`.

The composite distance is $`\langle x,kM\rangle_j=\log|(k^\top xk)_j|`, the vector of logarithms of the leading principal minors, read through the *total* form of the minors so that no positivity proof has to be carried into the definition of the transform. The boundary $`K/M=O(m)/D_{\pm1}` is represented by $`O(m)` itself with its Haar probability measure, in the coordinate-free form used throughout this development; that is legitimate because the composite distance is $`M`-invariant, and in these coordinates that invariance is the elementary `Matrix.cornerDet_conj_diagonal_sign` rather than a consequence of a uniqueness theorem Mathlib does not have.

$`\varrho` is *fixed*, as in the hyperbolic case, to $`(-\tfrac12,\ldots,-\tfrac12,(m-1)/4)`. That is the article's value, and it is right: with the composite distance in the minors, $`e^{(i\lambda+\varrho)\langle x,u\rangle}` is Terras' power function $`p_{\varrho+i\lambda}(x[k])` identically, so her contour $`\operatorname{Re}s=-\rho` with $`\rho=(\tfrac12,\ldots,\tfrac12,(1-n)/4)` — *Harmonic Analysis on Symmetric Spaces*, Thm 1.3.1(1) — transfers unchanged. An earlier version of this development recorded the article's $`\varrho` as a probable mis-transcription of the half-sum of the positive restricted roots. It is not; it is Terras' contour, and the entry has been withdrawn.

What remains parameters are $`|W|` and the `c`-function. Terras gives both explicitly, her $`c_n(s)` as a product of beta quotients and her $`\omega_n` as a product of gamma factors, and both now apply verbatim. The one thing not yet pinned is the conversion between her contour integral $`\mathrm ds` over $`\operatorname{Re}s=-\rho`, whose $`(2\pi i)^{-n}` sits inside $`\omega_n`, and Lebesgue measure $`\mathrm d\lambda` on $`\mathfrak a^*`, which is this development's convention. That is a computation, and the discipline here is that constants come out of proofs.

:::theorem "mathlib_spd_boundary" (lean := "SpdSpace.boundaryMatrix_mul, SpdSpace.boundaryMatrix_one, SpdSpace.signUnitary, SpdSpace.boundaryMatrix_signUnitary, SpdSpace.compositeDistance_mul_signUnitary, SpdSpace.helgasonFourier_mul_signUnitary") (uses := "mathlib_spd_model, mathlib_corner_det")
*The composite distance of $`\mathbb P_m` descends to the boundary $`K/M`.* Multiplying a boundary point on the right by a diagonal matrix of signs leaves the composite distance unchanged, and therefore leaves the Helgason--Fourier transform unchanged in its boundary argument. This is what makes an integral written over $`O(m)` an integral over $`K/M=O(m)/D_{\pm1}`: the integrand is constant on the fibres.
:::

The invariance of the *minors* under conjugation by a sign matrix is the earlier `Matrix.cornerDet_conj_diagonal_sign`, and it is not the same statement. That one is about conjugating a matrix; what the boundary integral needs is about multiplying a boundary point by an element of $`M`. The gap between the two is exactly the star-algebra equivalence between matrices and operators on `EuclideanSpace`, which is how the orthogonal group is presented throughout this development — coordinate-free, as the unitary group of an operator algebra. Being an algebra map it carries the sign matrices into the unitary group and turns a product of boundary points into a product of matrices, which closes the gap and nothing more is needed.

Recording it as a theorem rather than as a remark in the definition of the transform is the point. The total form of the minors has to be handled too: its junk value off the positive definite cone would break the invariance if the conjugation could leave the cone, and it cannot, because conjugating by an invertible symmetric matrix preserves positive definiteness in both directions.

:::theorem "mathlib_spd_cfunction" (lean := "SpdSpace.beta, SpdSpace.beta_eq, SpdSpace.beta_comm, SpdSpace.betaIntegral_eq_beta, SpdSpace.partialSum, SpdSpace.partialSum_apply, SpdSpace.partialSum_self, SpdSpace.blockLength, SpdSpace.blockLength_eq, SpdSpace.blockLength_self, SpdSpace.cIndex, SpdSpace.mem_cIndex, SpdSpace.cFactor, SpdSpace.cFactor_eq, SpdSpace.cFunction, SpdSpace.cFunction_eq, SpdSpace.cFunction_one, SpdSpace.cFunction_two, SpdSpace.weylConstant, SpdSpace.weylConstant_eq, SpdSpace.weylConstant_zero, SpdSpace.spdRho_apply, SpdSpace.spdRho_eq_neg_half_of_mem_Icc, SpdSpace.contourParam, SpdSpace.contourParam_apply, SpdSpace.re_partialSum_add_blockLength_eq_zero, SpdSpace.contourCFunction, SpdSpace.contourCFunction_eq, SpdSpace.plancherelDensity, SpdSpace.plancherelDensity_eq, SpdSpace.plancherelDensity_pos") (uses := "mathlib_spd_model, mathlib_helgason_inversion")
*Terras' explicit `c`-function and constant for $`\mathbb P_m`, transcribed.* $`c_m(s)=\prod_{1\le i\le j\le m-1}B(\tfrac12,s_i+\cdots+s_j+\tfrac12(j-i+1))/B(\tfrac12,\tfrac12(j-i+1))` and $`\omega_m=\prod_{j=1}^{m}\Gamma(j/2)/(j(2\pi i)\pi^{j/2})`, of *Harmonic Analysis on Symmetric Spaces*, Thm 1.3.1(1), together with her contour $`s=\varrho+i\lambda` and the Plancherel density built from them.
:::

This is a transcription and says so. Harish-Chandra's `c`-function is the integral $`\int_{\bar N}e^{-(i\lambda+\varrho)(H(\bar n))}\mathrm d\bar n`, which is what the abstract layer takes as its definition, and the identity between that integral and Terras' product of beta quotients is the Gindikin--Karpelevich formula for $`\mathbb P_m` — a theorem, not proved here, and no declaration claims it. Nor is the conversion from Terras' contour measure $`\mathrm ds` to Lebesgue measure $`\mathrm d\lambda` carried out, so $`\omega_m` keeps its $`2\pi i` literally rather than absorbing it into a real constant, and the order of the Weyl group stays a parameter: Terras' theorem carries no $`|W|^{-1}` at all, her whole constant being $`\omega_m`, so the split between $`|W|` and `c` is a convention that the same computation has to fix.

What *is* proved is the part where an error would be silent. The index range of the product is pinned by its two smallest cases — $`c_1(s)=1`, the empty product, and $`c_2(s)=B(\tfrac12,s_1+\tfrac12)/B(\tfrac12,\tfrac12)`, the single factor — and by the observation that on the contour the second argument of every numerator has real part *exactly* zero: a block runs from `i` to `j` with $`j+1<m`, so it misses the one exceptional coordinate of $`\varrho` and the shift contributes precisely $`-\tfrac12(j-i+1)`. That is also why the beta function here is the gamma quotient rather than Mathlib's Euler integral, which converges only for arguments of positive real part and is therefore undefined at exactly the values $`c_m` is evaluated at.
