import LeanRidgelet
import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false
-- Verso directive headers and display mathematics must stay on one physical line.
set_option linter.style.longLine false
set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Mathlib upstream candidates: groups and homogeneous spaces" =>
%%%
file := "to-mathlib-lie"
%%%

This chapter is the part of the upstream candidates that concerns *analysis on compact groups and their homogeneous spaces*. It is separated from the rest because Mathlib's coverage there is thinner than in Fourier and Schwartz analysis, because the remaining gap of this kind is the one open problem of the `d`-plane development, and because the same material is what a future treatment of the noncompact symmetric-space case would build on. The files live under `LeanRidgelet/ToMathlib/LieGroup/`.

What Mathlib does have is the abstract theory: Haar measure on a locally compact group, its uniqueness, and the unitary group of a C\*-algebra as a topological group. What it does not have is any of the concrete objects a reconstruction formula over a manifold of frames needs. The chapter supplies them in the order they depend on each other: the orthogonal group as a compact group with a Haar *probability* measure; the Stiefel manifold with a topology, a Borel structure and an invariant measure; uniqueness of the rotation-invariant measure on the sphere; the matrix polar integration formula that those two combine into; the identification of the Stiefel manifold at codimension one with the sphere; and the singular value decomposition.

One gap remains, and it is recorded at the end: the *Jacobian* of the singular value decomposition. It is the only piece of the `d`-plane development that is not formalized, it is needed for no proof — only to relate two parameter measures — and it is a project of its own, because it factors through Weyl's integration formula for real symmetric matrices, which Mathlib does not have either.

*The orthogonal group and the Stiefel manifold*

:::theorem "mathlib_orthogonal_group" (lean := "ContinuousLinearMap.instContinuousStar, ContinuousLinearMap.norm_le_one_of_mem_unitary, ContinuousLinearMap.isCompact_unitary, ContinuousLinearMap.instCompactSpaceUnitary, ContinuousLinearMap.orthogonalHaar, ContinuousLinearMap.instIsProbabilityMeasureOrthogonalHaar, ContinuousLinearMap.instTopologicalSpaceLinearIsometry, ContinuousLinearMap.continuous_toContinuousLinearMap, ContinuousLinearMap.unitaryIsometry, ContinuousLinearMap.stiefelAct, ContinuousLinearMap.stiefelAct_mul, ContinuousLinearMap.continuous_stiefelAct_left, ContinuousLinearMap.continuous_stiefelAct_right, ContinuousLinearMap.stiefelMeasure, ContinuousLinearMap.map_stiefelAct_stiefelMeasure, ContinuousLinearMap.instIsMulRightInvariantOrthogonalHaar, ContinuousLinearMap.isometryEquivOfIsometry, ContinuousLinearMap.unitaryOfIsometryEquiv, ContinuousLinearMap.exists_stiefelAct_eq, ContinuousLinearMap.stiefelMeasure_eq, ContinuousLinearMap.map_comp_right_stiefelMeasure") (uses := "mathlib_dplane_transform")
*The orthogonal group is a compact group, and the Stiefel manifold carries an invariant measure.* Mathlib has the orthogonal group only as linear algebra — `Matrix.orthogonalGroup` is a submonoid of matrices with no topology, no compactness and no measure — but it does have the unitary group of a C\*-algebra as a topological group whenever the star operation is continuous, and it identifies the elements of `unitary (E →L[𝕜] E)` with the linear isometry equivalences of `E`. That is the orthogonal group in coordinate-free form, and what is missing from it is supplied here: the adjoint is continuous because it is an isometry, so the group is topological; a unitary has operator norm at most one, so the group is bounded; it is closed, and in finite dimensions the operator space is proper, so it is *compact* by Heine--Borel; hence it carries a Haar measure, which is a *probability* measure because the group is compact.
:::

The Stiefel manifold of orthonormal `k`-frames is the space of linear isometries $`\mathbb R^k\to E`, which Mathlib leaves without a topology, a Borel structure or a measure. All three are given here, the topology induced from the continuous linear maps, and the *invariant measure* is defined as the pushforward of the Haar probability measure along the action of the orthogonal group on a fixed frame. Defining it this way makes invariance hold by construction rather than by a uniqueness theorem — which is what a construction by iterated sphere measures would need, since the recursion there privileges the first vector of the frame and the dependent family of orthogonal complements admits no global measurable trivialization.

Two further properties are what the matrix polar integration formula in codimension greater than one needs, and both are here. *Independence of the base frame*: the action is transitive on frames, because the map $`L'\circ L^{-1}` defined on the range of `L` extends to an isometry of all of `E` and in finite dimensions such an isometry is surjective, hence unitary; so the two pushforwards differ by a right translation of the group. That translation is invisible to the Haar measure because the group is *unimodular* — right translation of a left invariant measure is again left invariant, hence a scalar multiple of the Haar measure by uniqueness, and the scalar is the total mass, which compactness makes `1` on both sides. Mathlib derives right from left invariance only for abelian groups.

*Invariance under the right action* $`L\mapsto L\circ V` of the isometries of $`\mathbb R^k` then needs no separate argument: precomposing by `V` only replaces the frame the measure is built from, and by the previous paragraph every frame gives the same measure. This is the property that makes the direction integral of the matrix polar formula independent of the point of $`\mathbb S^{k-1}` it is read at.

*The sphere*

:::theorem "mathlib_sphere_invariant_measure" (lean := "MeasureTheory.sphereAct, MeasureTheory.continuous_sphereAct, MeasureTheory.coe_image_preimage_sphereAct, MeasureTheory.smul_set_preimage_isometryEquiv, MeasureTheory.map_sphereAct_toSphere, MeasureTheory.unitVectorIsometry, MeasureTheory.exists_sphereAct_eq, MeasureTheory.sphereOrbitMeasure, MeasureTheory.sphereOrbitMeasure_apply, MeasureTheory.sphereOrbitMeasure_eq, MeasureTheory.toSphere_eq_smul_sphereOrbitMeasure, MeasureTheory.sphereOrbitMeasure_eq_smul_toSphere, MeasureTheory.frameDirection, MeasureTheory.continuous_frameDirection, MeasureTheory.map_frameDirection_stiefelMeasure") (uses := "mathlib_orthogonal_group, mathlib_polar_coordinates")
*The rotation-invariant measure on the unit sphere is unique.* Mathlib records how `Measure.toSphere` is computed but none of its symmetries. *Invariance* under the orthogonal group is the first declaration group: `Measure.toSphere_apply'` computes $`\mu_{\mathbb S}(s)` as $`\dim E` times the Lebesgue measure of the open cone $`(0,1)\cdot s`, a rotation carries that cone to the cone over the rotated set, and Lebesgue measure does not see a rotation. *Uniqueness* is the averaging argument: the orbit measure of a unit vector — the pushforward of the Haar probability measure along $`Q\mapsto Qv` — does not depend on `v`, because the action is transitive and the Haar measure is unimodular; and averaging the invariance of the surface measure over the group, then exchanging the two integrals, identifies the surface measure with its total mass times that orbit measure. Transitivity on the sphere is the $`k=1` case of transitivity on frames, a unit vector being a linear isometry of the line.
:::

The consequence the matrix polar integration formula needs is the last declaration: *the direction of a random frame is uniform on the sphere.* For a fixed unit vector $`\boldsymbol\omega` of the frame space, the pushforward of the invariant measure on the Stiefel manifold along $`U\mapsto U\boldsymbol\omega` is the normalized surface measure, whichever $`\boldsymbol\omega` is chosen and whichever frame the Stiefel measure was built from. Both halves of the proof are what the two constructions were for: the orbit map of a *frame* composed with the direction map is the orbit map of a *vector*, and the orbit measure of a vector is the normalized surface measure by uniqueness.

*The matrix polar integration formula*

:::theorem "mathlib_matrix_polar" (lean := "MeasureTheory.toSphere_real_smul_integral_directionAverage, MeasureTheory.toSphere_real_smul_integral_stiefelMeasure, MeasureTheory.radialIntegral, MeasureTheory.radialLIntegral, MeasureTheory.measurable_radialLIntegral, MeasureTheory.toSphere_mul_lintegral_directionAverage, MeasureTheory.toSphere_mul_lintegral_stiefelMeasure, MeasureTheory.continuous_frameApply, MeasureTheory.ae_integrable_weighted_frameSection, MeasureTheory.integrable_prod_radialIntegral, MeasureTheory.toSphere_real_smul_integral_stiefelMeasure_of_stronglyMeasurable") (uses := "mathlib_sphere_invariant_measure, mathlib_orthogonal_group, mathlib_polar_coordinates")
*The matrix polar integration formula.* Polar coordinates write an integral over $`\mathbb R^m` as an integral over $`\mathbb S^{m-1}\times(0,\infty)`; the matrix polar formula does the same with a `k`-frame in place of a direction,
$$`c_{m,k}\int_{\mathbb R^m}F=\int_{V_{m,k}\times\mathbb R^k}F(U\boldsymbol b)\,|U\boldsymbol b|^{m-k},`
and it is what the `d`-plane reconstruction formulas need in codimension greater than one. The proof is three reductions and no new analysis: polar coordinates on the frame space turn the weight $`|U\boldsymbol b|^{m-k}` together with the Jacobian $`r^{k-1}` into $`r^{m-1}`, which is the Jacobian of polar coordinates on $`\mathbb R^m`; the direction integral over frames becomes an integral over $`\mathbb S^{m-1}` because the direction of a random frame is uniform there; and polar coordinates on $`\mathbb R^m` put it back together.
:::

Since the invariant measure on the Stiefel manifold is normalized to a *probability* measure, the constant comes out as a ratio of sphere areas, $`|\mathbb S^{k-1}|/|\mathbb S^{m-1}|`, and the statement is written multiplied out so that no division appears. That form is independent of how the Stiefel manifold is normalized. In the classical normalization, where the Stiefel manifold carries total mass $`\sigma_{m,k}=\prod_{j<k}|\mathbb S^{m-1-j}|`, the constant becomes $`|\mathbb S^{k-1}|\cdot\sigma_{m-1,k-1}` — the article's $`c_{m,k}` with frames of the *orthogonal complement* of the direction rather than of the whole space. The two readings agree at $`k=1`, which is why the codimension-one development did not see the difference.

The middle move is stated separately as the *direction average*, the first declaration: averaging a function of the direction $`U\boldsymbol\omega` over frames and over unit vectors of the frame space is averaging it over $`\mathbb S^{m-1}`, up to the ratio of the two sphere areas. That is the shared core of the reconstruction formulas over the Stiefel manifold and over the similitude group — whatever the weight family, the derivation ends by reducing the parameter integral to this average — so it is worth having on its own rather than inlined.

Both reductions are Tonelli rather than Fubini when read for the lower Lebesgue integral, so the *unsigned* form of the formula needs no hypothesis but measurability — and there the frame section needs no almost-everywhere qualifier either, a frame being an isometry, so the weight $`|U\boldsymbol b|^{m-k}` is $`|\boldsymbol b|^{m-k}` and the reduction holds at every frame.

That is what discharges the absolute convergence of the signed formula, which the article carries as a standing assumption: for a *strongly measurable* integrand, both hypotheses — the weighted section along almost every frame, and the doubly iterated integrand on the product — follow from integrability, by computing the integral of the norm with the unsigned formula and reading off that almost every fibre is finite.

The measurability cannot be weakened to almost-everywhere measurability, and the reason is not a technicality. The left-hand side reads the integrand only along the ranges of the frames, each of which is a null set of `E` when $`k<m`; an integrable integrand may therefore be modified there — off a null set of `E`, so without disturbing the right-hand side — into one whose frame sections are not even measurable. What the unsigned formula does say is that a *measurable* null set is met in a null set by almost every frame, so the formula is insensitive to modifying a strongly measurable integrand on a null set even though no individual frame section is.

*Codimension one*

:::theorem "mathlib_stiefel_codim_one" (lean := "MeasureTheory.continuous_frameOfUnitVector, MeasureTheory.stiefelHomeomorphSphere, MeasureTheory.stiefelHomeomorphSphere_apply, MeasureTheory.measurePreserving_stiefelHomeomorphSphere, MeasureTheory.integral_stiefelMeasure_codimOne") (uses := "mathlib_sphere_invariant_measure, mathlib_dplane_transform")
*The Stiefel manifold at codimension one is the unit sphere.* The set-level identification is in `mathlib_dplane_transform` and the measure theory of the two sides is in `mathlib_sphere_invariant_measure`; this joins them. The identification is a *homeomorphism*: sending a frame to its unit vector is continuous because the topology on the Stiefel manifold is induced from the continuous linear maps, and sending a unit vector to the frame that scales it is continuous because that frame is the coordinate functional tensored with the vector, a bounded bilinear operation. Reading "the direction of a random frame is uniform on the sphere" through the identification then makes it *measure preserving*, onto the surface measure divided by its total mass — the only difference between the two sides being that the invariant measure on the Stiefel manifold is normalized to a probability measure and `Measure.toSphere` is not.

The change of variables for integrals follows with no measurability hypothesis on the integrand, the substitution being along an equivalence. Its use is to make "the general codimension specializes to codimension one" a theorem about the two layers rather than a remark about two constructions that resemble each other.
:::

*Matrix decompositions*

:::theorem "mathlib_svd" (lean := "MeasureTheory.linearMapOfFamily, MeasureTheory.linearMapOfFamily_apply, MeasureTheory.isometryOfOrthonormalFamily, MeasureTheory.isometryOfOrthonormalFamily_apply, MeasureTheory.isometryOfOrthonormalFamily_single, MeasureTheory.exists_svd") (uses := "mathlib_diagonal_scaling")
*Singular value decomposition of an injective linear map.* Mathlib has singular *values* — `LinearMap.singularValues`, the square roots of the eigenvalues of $`A^\top A` — but not the decomposition they are the values of. It is proved here in the case that integration over a matrix space needs: an injective $`A:\mathbb R^k\to E` factors as $`A=UDV^\top` with `U` an orthonormal `k`-frame, `V` a rotation of $`\mathbb R^k`, and `D` the coordinatewise scaling by `k` *positive* numbers.

The proof is the spectral theorem and nothing else. $`T=A^\top A` is symmetric, and positive definite because `A` is injective; its orthonormal eigenbasis $`(b_i)` has eigenvalues $`\mu_i=\|Ab_i\|^2>0`; the vectors $`u_i=Ab_i/\sqrt{\mu_i}` are orthonormal in `E` because $`\langle Ab_i,Ab_j\rangle=\langle Tb_i,b_j\rangle=\mu_i\delta_{ij}`; and reading `A` in the two bases gives the factorization with $`d_i=\sqrt{\mu_i}` and `V` the basis change. One auxiliary construction is worth naming on its own: an orthonormal family indexed by `Fin k` *is* a linear isometry out of $`\mathbb R^k`, sending the standard basis to the family.

What is *not* here is the measure-theoretic half — the Jacobian $`\mathrm dA=\delta(D)\,\mathrm dD\,\mathrm dU\,\mathrm dV`, which is what turns an integral over the matrix space into one over the singular value coordinates. Its published proofs go through exterior differential forms, or through the Jacobian of the matrix polar decomposition together with Weyl's integration formula for real symmetric matrices, and Mathlib has none of those.
:::
